### ISSUE TITLE
[Bug]: Finishing with mpv-android does not mark video as watched

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#891] opened 2023-05-20 09:03 UTC
### Problem description

Basically as the title says. I'm currently using mpv-android (set as standard external player in Nova) as it supports ass subtitles. However, after finishing an episode it switches back to Nova without marking the episode as watched.

### Steps to reproduce the issue

Use mpv as standard external player, finish episode.

### Your phone/tablet/androidTV model

pixel 7/Samsung Tab A7

### Operating system version

yes

### Application version and app store

6.2.8

**Comment by courville** [comment] 2023-05-26 17:44
Grumf... https://github.com/nova-video-player/aos-AVP/issues/758 ok this is now mpv-android turn.
For later reference this is the intent documentation http://mpv-android.github.io/mpv-android/intent.html
FTR it seems to be the same as for mxplayer and it should be working.

**Comment by ghost** [comment] 2023-05-26 17:57
Sorry that I seem to be going from player to play to point out what is not working!

**Comment by courville** [comment] 2023-05-26 18:05
No problem.
I tried to reproduce the issue with mpv and on my side the video is marked as watched.

**Comment by ghost** [comment] 2023-05-26 18:27
Interesting. When I just return from the video myself it saves my last played spot and if I do it at the end of the video manually it gets marked as watched. If I just wait for the video to end naturally and go back to Nova it does not work.

**Comment by courville** [comment] 2023-05-26 20:17
OK this is actionable info for reproducing: it turns out then when video is completed, what is returned is that position=0 (i.e. video has not started):
```
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: requestCode=989, resultCode=-1, mVideoDbInfo!=null true, mPlayerUri http://localhost:44617/Succession.S04E07.720p.HEVC.x265-MeGusta[eztv.re].srt
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: data.getData()=null
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: JUSTPLAYER_RESULT_EXTRA_end_by=null, VLC_RESULT_EXTRA_position=-1, JUSTPLAYER_RESULT_EXTRA_duration=-1, VLC_RESULT_EXTRA_duration=-1, requestCode=989, resultCode=-1
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: position=0, duration=11348000
```
I guess that I can trap this and say start=end...
At least mxplayer and other players (e.g. justplayer) throws in this case a "playback_completion" extra when returning 0 position.
Note that this is not compliant with mxplayer behavior https://mx.j2inter.com/api that mpv-android states to mimic.
I would be tempted to file a bug on mpv github instead of building yet another workaround.

**Comment by courville** [comment] 2023-06-03 11:36
Looking at what returns the different players watching to the end a video:
* JustPlayer:
```
D/com.archos.mediacenter.video.utils.ExternalPlayerResultListener( 5710): onActivityResult: data end_by : playback_completion
D/com.archos.mediacenter.video.utils.ExternalPlayerResultListener( 5710): onActivityResult: data.getData()=Bundle[{end_by=playback_completion}]
```
* vlc:
```
D/com.archos.mediacenter.video.utils.ExternalPlayerResultListener( 5710): onActivityResult: data is null!
```
* mpv:
```
D/com.archos.mediacenter.video.utils.ExternalPlayerResultListener( 5710): onActivityResult: data.getData()=null
```
It means that to capture more cases having data `null` or `data.getData()=null` means video watched.

**Comment by ghost** [comment] 2024-03-26 19:40
Seems fixed, thanks!

**Closed as completed** 2024-03-26 19:39 UTC
Labels: bug
