### ISSUE TITLE
3.6 External subtitles not listed in the subtitles menu

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#114] opened 2019-04-27 13:37 UTC
Installing 3.6 saw that subtitles will not load.
It somehow broke the app so bad that even reverting to 3.2 does not help - subtitles no longer work.

I deleted data, cache, uninstalled 3.6 restarted tv, installed 3.2 - still no external subtitles.
Only integrated ones work.

What can I try?
This is really nasty.

Subtitles in 4.2 do not work too.
Playback buttons in 4.2 are much better now btw.

**Comment by JJD2K** [comment] 2019-04-27 13:49
Update: 3.2 fixed itself. Don't know how but after indexing was done now working.
Maybe something because of indexing as I did not change anything else.

**Comment by courville** [comment] 2019-04-27 13:57
First please be more specific in your issue description. Disaster is not really helping understanding the problem.
I tried to reproduce your subs loading issue and it does not happen on my side (not saying that the issue is not present) both on 3.6 and 4.2.
3.2 "fixing by itself" hints towards an indexing issue.
Perhaps this is due to going from 4.x to 3.x back and forth.
Please re-open the issue if you find a way to reproduce.

**Comment by JJD2K** [comment] 2019-04-27 15:12
I wrote disaster as it was impossible to go back to a working version - thought that some settings or changes in the index file have been done.
The only thing I did is to install 3.6 over 3.2 - susbtitles were missing.
As I had to go to 3.2 to fix this I decided to install 4.2 for a test - subtitles were missing there too.
What I did next is to uninstall 4.2 in order to install 3.2 as otherwise the installer does not want to install 3.2 over 4.2.
Installed 3.2 - it was not working so I did what I described in my initial post.

In both versions the SRT file is displayed in the file info screen, but in the subs menu there is no SRT option to select.

**Comment by JJD2K** [comment] 2019-04-27 15:18
I see no option to re-open this.

**Comment by courville** [comment] 2019-04-27 16:13
I tried to reproduce the issue on leanback interface (androidtv) and cannot both on 4.2 and 3.6 via samba.
SRT subtitle listed in VideoInfo view and it loads fine.
The only issue I can think of if subtitle is listed in VideoInfo is that it fails to be downloaded for whatever reason when playback is launched.
Will monitor this.

**Comment by JJD2K** [comment] 2019-04-27 16:56
I do not have the SRT option in the subtitles menu at all.
I tried with multiple files.

**Comment by JJD2K** [comment] 2019-04-27 23:54
I tried this again and now it is working - do not know what happened the first time.
3.6 is quite slower decoding than 3.2 though and the audio menu is in front of the subs one.

**Comment by courville** [comment] 2019-04-28 07:55
I am able to reproduce some behavior that could coincide with your issue.
Cf. https://github.com/nova-video-player/aos-AVP/issues/119
This is not a regression and has been there for a while.
Let's close this issue and track it in the new one if we do not find any evidence that these are not related.
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/119

**Closed as completed by courville** 2019-04-28 07:55 UTC
