### ISSUE TITLE
[Bug]: Hide Subtitles by Default setting doesn't work anymore.

### ISSUE THREAD

**Issue by buthig666** [nova-video-player/aos-AVP#968] opened 2023-10-10 15:41 UTC
### Problem description

Hide Subtitles by Default setting no longer ... hides subtitles by default.  I don't see this problem mentioned by anyone else so I am assuming it could be a corruption on my end or with my model tv.  ???  Any basic advice would be appreciated.  It has been this way for a couple of nightly builds for a little while.

### Steps to reproduce the issue

Toggle the feature in settings.  Turn subs to none in a movie file.  Force close the app.  Open back up the app and movie file.  Subs are on again.  I have to turn subs off on every single video file even if resuming.  I have cleared cash, same behavior.  I have uninstalled and reinstalled then restarted, same behavior.  

### Expected behavior

Hide subtitles by default.

### Your phone/tablet/androidTV model

Sony Bravia 43x85J

### Operating system version

Android 10

### Application version and app store

6.2.30 

### Additional system information

Thanks for all the work you do.

**Comment by courville** [comment] 2023-10-10 18:07
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/957

Hopefully fixed in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.31

**Closed as completed by courville** 2023-10-10 18:07 UTC
Labels: bug, duplicate

**Comment by buthig666** [comment] 2023-10-12 11:52
Thank you Courville.
