### ISSUE TITLE
playback issue on Sony MTK for some HEVC videos

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#153] opened 2019-05-25 18:15 UTC
No hardware decoding on SonyTV - unplayable - plays ok on MX and KODI.
Codec: MPEG-H Part2/HEVC (H.265) (hevc)

**Comment by courville** [comment] 2019-05-25 18:19
You are right, some HEVC (not all) do not play on Sony TV. I reproduced it and it is the case since the first nova submission (thus not a regression).
We will look into it.
When doing such a report if you can please provide the faulty sample or at least a portion of it.
But no need there since I am able to reproduce on some clips that I have.

**Comment by JJD2K** [comment] 2019-05-25 18:25
Would be glad to, but those are all very large files.

**Comment by michaelkociansde** [comment] 2019-08-21 14:42
This issue is still present on my Sony TV.

**Comment by courville** [comment] 2019-08-29 16:15
See https://github.com/nova-video-player/aos-avos/commit/0f265912723c672b37848696363b4dfa9eeca415 and https://github.com/nova-video-player/aos-avos/commit/c12725a8e3105c8d6069af6e6041dad3117f9c9e

**Comment by courville** [comment] 2019-08-29 16:21
Please try https://github.com/nova-video-player/aos-AVP/releases/tag/v4.12 and report if there is any improvement.

**Comment by JJD2K** [comment] 2019-08-30 06:15
More formats are now supported. Files that did not play before are now working. Unfortunately the performance is not good yet.

**Comment by JJD2K** [comment] 2019-09-05 12:25
The branch is very unstable yet - it exits.
Also it does not display recently played, recently added for a very long time upon startup - until you enter movies or tv series sections.

**Comment by courville** [comment] 2019-09-06 06:51
> Also it does not display recently played, recently added for a very long time upon startup - until you enter movies or tv series sections.

Thanks for this feedback: I will put some logs to trace this non systematic behavior.

**Comment by courville** [comment] 2019-09-06 21:22
OK for the recent instability you report, I might have an idea of the problem: could you confirm that you have tv channels enabled? If so please disable all channels on the home screen related to nova and report if it suppresses the issue. Thx

**Comment by JJD2K** [comment] 2019-09-06 21:38
Hello
I do not uderstand what you mean. I have no channels enabled - I do not even use the tv tuner.
Version 4.X has never been stable for me from the very beginning - it is laggy and the interface is flickering and repaiting very slowly. Paint issues are all over the tool - entering a movie/series section, exiting to the main screen, slow update of items on startup and many more.
What I reported is not non-systematic - when I start the app only movies and tv shows sections are available - 2 rows on the startup page. I have to enter/exit one of those in order for the rest of the rows to appear.  The latest version also exits (crashes maybe) while playing or navigating through the interface.
According to my experience version 4.X is at an early alpha stage. I am sorry to say this....

**Comment by courville** [comment] 2019-09-15 12:12
Closing the issue based on latest modifications https://github.com/nova-video-player/aos-avos/commit/0f265912723c672b37848696363b4dfa9eeca415 and https://github.com/nova-video-player/aos-avos/commit/c12725a8e3105c8d6069af6e6041dad3117f9c9e that should help with HEVC playback on MTK based devices.
These modifications are available on latest beta on Google Play.
I propose to open a specific new issue to track any problem that are appearing starting v4.14.

**Closed as completed by courville** 2019-09-15 12:12 UTC
