### ISSUE TITLE
[Bug]: After fast forwarding, video stuck a double speed

### ISSUE THREAD

**Issue by eng3** [nova-video-player/aos-AVP#1257] opened 2024-07-22 14:49 UTC
### Problem description

Often, after fast forwarding to skip ahead a large amount, the video will play at double speed.  I must exit the app and start it again, resuming the video, then it will play at normal speed

### Steps to reproduce the issue

Start video, fast forward a few minutes.  Often, video will be stuck at double speed.

### Your phone/tablet/androidTV model

Nvidia Shield 2019 Pro

### Operating system version

11

### Application version and app store

6.2.90 from play store

**Comment by courville** [comment] 2024-07-22 17:11
I think this is a duplicate of https://github.com/nova-video-player/aos-AVP/issues/1232
Closing the issue.

**Closed as completed by courville** 2024-07-22 17:11 UTC
Labels: bug, duplicate
