### ISSUE TITLE
[Bug]: cannot resume show after pausing

### ISSUE THREAD

**Issue by mklcw** [nova-video-player/aos-AVP#920] opened 2023-08-06 04:21 UTC
### Problem description

cannot resume show after pausing for more than a certain time frame. Maybe 15 minutes.
When trying to resume the show again, it will jump back to previous screen and progress will be lost.
It happens while playing shows on webdav. 

### Steps to reproduce the issue

Pause show stored on webdav for more than 15 minutes, resume doesn't work

### Expected behavior

Progress lost. 

### Your phone/tablet/androidTV model

Mibox 4

### Operating system version

Android 9

### Application version and app store

6.2.17 from github

**Comment by courville** [comment] 2024-02-04 15:23
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/674. Let's follow progress on the earlier issue.

**Closed as completed by courville** 2024-02-04 15:23 UTC
Labels: bug, duplicate
