### ISSUE TITLE
Problem open HEVC/H.265 Video since version 3.0

### ISSUE THREAD

**Issue by duckyngo** [nova-video-player/aos-AVP#71] opened 2019-03-18 08:53 UTC
I open the video with format HEVC/H.265 in the lasted code and the application can't load video. I tried with the version V2.1 that work. Please check the issue.

**Comment by courville** [comment] 2019-03-18 09:14
Can you please disclose your hardware configuration?

**Comment by duckyngo** [comment] 2019-03-18 12:59
I have 2 devices. One is Xiaomi Redmi 5 plus and another is LG Nexus 5. Both of them have this problem

**Comment by courville** [comment] 2019-03-19 06:05
Indeed thanks for reporting.
It seems that HEVC software decoding is broken and on the devices you mention there is not hardware decoding support which explains the issue.
We will fix it.

**Comment by JJD2K** [comment] 2019-03-19 17:03
Actually it does not work on Sony TV too - I think it was working in ARCHOS even better than x264.

**Comment by courville** [comment] 2019-03-20 06:34
> Actually it does not work on Sony TV too - I think it was working in ARCHOS even better than x264.

we are not talking about hevc hardware decoding, on swdec here.
swdec is used only when hwdec is not available and for generating tv image when scraping is not working.
This is due to a regression when upgrading ffmpeg library to latest one incorporating dav1d video codec support.

**Comment by courville** [comment] 2019-04-04 11:53
Reproduced on sony tv with one HEVC sample (not all). It is not a regression, issue happens also with 2.1 version.
Note that the problem with the phones are thus possibly uncorrelated.
Trying to get my hands on an old nexus 5.

**Comment by courville** [comment] 2019-04-09 11:29
On nexus4 on Android L avos ko:
```
V/LibAvos ( 1962): Can't load library: java.lang.UnsatisfiedLinkError: dlopen failed: library "libdav1d.so.0" not found
V/LibAvos ( 1962): Can't load library: java.lang.UnsatisfiedLinkError: dlopen failed: library "libdav1d.so.0" not found
V/LibAvos ( 1962): Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.courville.nova-2/base.apk"],nativeLibraryDirectories=[/data/app/org.courville.nova-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libcryptocompat.so"
V/LibAvos ( 1962): Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.courville.nova-2/base.apk"],nativeLibraryDirectories=[/data/app/org.courville.nova-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsslcompat.so"
V/LibAvos ( 1962): Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.courville.nova-2/base.apk"],nativeLibraryDirectories=[/data/app/org.courville.nova-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libcurl.so"
```

**Comment by courville** [comment] 2019-04-17 13:07
Thus for pre-M Android versions this was needed https://github.com/nova-video-player/aos-dav1d-android-builder/commit/8300e9a68b3e232f655085a7519f11086046ae5f
Now fixed.

**Closed as completed by courville** 2019-04-17 13:07 UTC
