### ISSUE TITLE
[Bug]: 6.0.75 makes video stutters / no smooth playback anymore

### ISSUE THREAD

**Issue by mitch133** [nova-video-player/aos-AVP#726] opened 2022-10-24 16:16 UTC
### Problem description

All my movies slightly stutters since 6.0.75 Google Play Release

### Steps to reproduce the issue

Play any movie and see how it's not smooth

### Expected behavior

Videos should play normally, as they did till 6.0.74

### Your phone/tablet/androidTV model

Freebox Pop

### Operating system version

Android 10 (beta)

### Application version and app store

6.0.75 Google Play

### Additional system information

Maybe due to the new and experimental playback functionnality

**Comment by courville** [comment] 2022-10-24 18:06
Unfortunately I cannot reproduce on nvidia shield and pixel6 phone. Might be pop specific. Will try on another amlogic when I get a chance.

**Comment by mschumacher69** [comment] 2022-10-24 22:06
Try disabling automatic refresh rate switch. This might not be 6.0.75 specific, but it started happening to me randomly since the latest update to my Chromecast with Google TV from Android 10 to Android 12.

I turned off automatic refresh rate switch both in the Google TV settings and Nova settings which seems to have resolved the issue.

**Comment by mitch133** [comment] 2022-10-25 07:53
@mschumacher69, thanks for your answer. The automatic refresh rate is already disabled in Nova. In fact, I need this function active and I discovered it worked better if disabled in Nova but enabled in system parameters. I need it for movies like Gemini man which play in 60fps. It works nice this way, in Kodi, Plex, and Nova (till 6.0.74 at least).

**Comment by buthig666** [comment] 2022-10-25 12:13
Same issue for me.  On Sony bravias, Android 11 and 10.  Video stutters on network play.  I love Nova but had to move back to vlc.

**Comment by mitch133** [comment] 2022-10-25 12:33
Indeed, I play movies over network (SMB) as well.

**Comment by buthig666** [comment] 2022-10-25 22:56
Ok after going back and testing both of my Sony Bravias, I would like to clarify if it helps devs identify the problem.

I am only using the tvs for network shared files (SMB.)  One Sony is an Android 10 and the other Android 9 (sorry I misspoke earlier.)  The Android 10 device doesn't seem to be stuttering for me, though the A9 clearly does after the latest update.

Settings regarding SMB2 or framerate match have zero affect.  Hope that helps.

**Comment by kparal** [comment] 2022-10-26 11:59
I have Sony Bravia KD-55XE8596 with Android 9. Two weeks back, Nova was playing my TV series (1080p) just fine. Yesterday, it was stuttering horribly. I have Nova 6.0.75. I tried toggling automatic refresh rate, doesn't help. Hardware decoding is on (when it's disabled, it's unwatchable). Disabling subtitles doesn't help. Stuttering occurs both when playing over SMB and **locally from a thumbdrive**, so this is not about SMB.

Something in Nova 6.0.75 really broke the playback on certain devices.

**Comment by t00gee** [comment] 2022-10-26 12:24
Same problem for me since the last update on my Philips 55OLED706. I guess I'll revert to the previous version and I'll stop the automatic updates.

**Comment by courville** [comment] 2022-10-26 16:30
Thanks for the feedback: could you please test this build that deactivates the playback speed feature in order to figure out if the regression comes from this one or the ffmpeg upstep:
 https://drive.google.com/file/d/1i8ETPFNh9-klB46phDjECZHFz_TR42s_/view?usp=sharing ?
In you tests please make sure you have deactivated audio passthrough (just to be sure on the supported mode autodetected added in this release too).
Thanks for the help in testing.

**Comment by mitch133** [comment] 2022-10-26 16:45
Hi, I downloaded it but cannot install it... At the end of the process I'm notified the installation could'nt complete.
Do we have to remove the previous installation of Nova? I still have 6.0.75. Maybe this is due to the release number if it hasn't changed?

**Comment by buthig666** [comment] 2022-10-26 17:01
I had to remove the previous nova.  After struggling with it a bit I was able to log into my smb and I didn't test extensively but can attest that at least 3 different files that were previously stuttering are not anymore.  Tested on Sony X9500G Android 9.

**Comment by courville** [comment] 2022-10-26 17:37
OK thanks for the quick feedback. This means somehow that I might have to enable playback speed control only for Android 10+... Let's try this.

**Comment by buthig666** [comment] 2022-10-26 18:09
Shrugs....  Your the boss.  I'm just happy you are taking the time to work on it on our behalf.

**Comment by mitch133** [comment] 2022-10-26 18:11
Works fine for me too. But I have to remind you I do have an Android 10 system, so you may implement the playback speed feature starting Android 11?

**Comment by buthig666** [comment] 2022-10-26 18:14
I don't notice any stuttering on my sony x85j Android 10...  Maybe it's there ever so slightly.  Or maybe it's a different problem ????

**Comment by buthig666** [comment] 2022-10-26 18:15
The difference could also be that my A10 is a google tv and my A9 is an Android tv with the google tv skin...  pretty much the same thing but they are a little different

**Comment by mitch133** [comment] 2022-10-26 18:24
On Android 10, the stuttering was indeed a little stuttering, but enough for me to notice it. Sound did not stutter, just image. Stuttering on Android 12 is due to the downmix issue reported in some other ticket with EAC3 7.1 tracks. No problem with AC3 5.1, DTS 5.1 or AAC (independently of the channel numbers)

**Comment by t00gee** [comment] 2022-10-26 18:33
My Philips 55OLED706 is Android TV v11 and I got the stuttering with v6.0.75. However the test version which @courville posted earlier seems to have fixed the problem. This means that playback speed control problem is not Android version related..

**Comment by courville** [comment] 2022-10-26 21:02
I have rolled out a new version that disables playback speed control to be on the safe side.
I have another test release that enables playback speed control only on android 10+: https://drive.google.com/file/d/1hLlEiJvvUsiY8JVypvKGD1FOjoy_AQRq/view?usp=sharing
Please test and report if it is still ok on your side.
Thanks for the testing and quick feedback loop.

@mitch133, I know you are on Android 10(beta) and it seems to work for others on an Android 10.
Let's see if I get other fail reports on other hardware with Android 10 before requesting Android 11+.
I will ask some free gurus what they think about it.

**Comment by courville** [comment] 2022-10-26 21:16
OK, I tested on a miproj amlogic based Android 9 device and audio speed control works.
I will thus need to find another solution (i.e. when on 1.0x do not try to apply setSpeed on PlaybackParams from AudioTrack since feature has been added in API23).

**Comment by mitch133** [comment] 2022-10-26 23:13
Hi @courville, ok, got it. For what you confirm in your last post, it's not related to Android's version. 
As a consequence, is there still a need to test your last release? Or is it fine to stay with 6.0.76 for now?

**Comment by kparal** [comment] 2022-10-27 21:51
> I have Sony Bravia KD-55XE8596 with Android 9. Two weeks back, Nova was playing my TV series (1080p) just fine. Yesterday, it was stuttering horribly. I have Nova 6.0.75. I tried toggling automatic refresh rate, doesn't help. Hardware decoding is on (when it's disabled, it's unwatchable). Disabling subtitles doesn't help. Stuttering occurs both when playing over SMB and **locally from a thumbdrive**, so this is not about SMB.

I can confirm that 6.0.76 fixed the stuttering on my TV. Thanks a lot for a quick response.

**Comment by mschumacher69** [comment] 2022-10-28 14:50
Not sure if it's the same issue or not, but now when I play 1080p x265 videos, every 4-5 min of play back, it skips a few seconds and starts stuttering until I rewind or exit and re-enter playback.

This is also happening on  6.0.76.

**Comment by courville** [comment] 2022-10-28 16:43
OK another test to be made with 6.0.77: I re-enabled playback speed control (that works depending on the device) but avoided to change audio speed if the speed is set to 1.0x. Thus it should not cause stuttering if speed is not changed (finger crossed). Please let me know if it is ok on your side. Pre-release is available here: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.77

**Comment by courville** [comment] 2022-10-28 16:59
> Not sure if it's the same issue or not, but now when I play 1080p x265 videos, every 5-10 min of play back, it skips a few seconds and starts stuttering until I rewind or exit and re-enter playback.
> 
> This is also happening on 6.0.76.

This should not be related to this problem unfortunately.

**Comment by mitch133** [comment] 2022-11-02 00:02
> OK another test to be made with 6.0.77: I re-enabled playback speed control (that works depending on the device) but avoided to change audio speed if the speed is set to 1.0x. Thus it should not cause stuttering if speed is not changed (finger crossed). Please let me know if it is ok on your side. Pre-release is available here: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.77

No stuttering on my side with 6.0.77

**Comment by Molasar49** [comment] 2022-11-03 01:29
Can confirm v.6.0.76 has this same issue too on FireTV (Fire OS 7.6.0.8)

**Comment by kparal** [comment] 2022-11-07 20:24
Heavy stuttering is back on [my TV](https://github.com/nova-video-player/aos-AVP/issues/726#issuecomment-1291924958) with version `6.0.80`. `6.0.75` was stuttering, `6.0.76` was smooth, and I was still waiting for `6.0.77` to appear in Google Play so that I can test it, but I was surprised to see `6.0.80` instead. It's broken again.

Can we please reopen this issue?

**Comment by courville** [comment] 2022-11-07 20:27
@kparal, do you confirm that you are not using a different playback speed?

**Comment by kparal** [comment] 2022-11-07 20:34
> @kparal, do you confirm that you are not using a different playback speed?

No, I'm not. I didn't even know it was possible, but I found the menu now and checked it, it's at `x1.00`. As before, I also tried toggling refresh rate autoadjust and disabling subtitles, no change.

**Comment by courville** [comment] 2022-11-07 20:53
@mitch133, @t00gee could you confirm on your side that stuttering is back on 6.0.80?
I do not quite see what I changed between the two versions that could cause this.

**Comment by mitch133** [comment] 2022-11-07 21:42
@courville @kparal No stuttering here, both of my devices play movies well with 6.0.80, reason why I had previously closed this issue

**Comment by courville** [comment] 2022-11-07 22:08
@kparal just to be on safe side, could you please retest with no adaptive refresh rate, no passthrough? I do not see what changed on this front from 6.0.77 and 6.0.80 (apart from other issues corrected).

**Comment by buthig666** [comment] 2022-11-08 00:00
Just quickly tested no ad re rate and no passthru...  It's definitely still a problem.  When I set Vlc as player no stutter.

**Comment by kparal** [comment] 2022-11-08 07:03
> could you please retest with no adaptive refresh rate, no passthrough?

I don't use passthrough and I tested adaptive refresh rate on and off, stuttering always.

> I do not see what changed on this front from 6.0.77 and 6.0.80

The problem might be in the changeset between 6.076 and 6.077. Because 6.077 never appeared for me on Google Play, I could never test it. I might have some time today, I'll try to figure out if I can sideload 6.077 apk directly into my TV and test it. A stupid question, but how do I figure out which apk architecture I should use? Should I go with "universal", are there any drawbacks?

(Or is the GPlay Beta channel also available for TVs? That would simplify things).

**Comment by mschumacher69** [comment] 2022-11-08 07:14
> A stupid question, but how do I figure out which apk architecture I should use? Should I go with "universal", are there any drawbacks?

You can go with universal, but the apk is double the size. The easiest way to know which architecture to use is to simply try, the wrong one will not install.

**Comment by courville** [comment] 2022-11-08 08:09
Thanks for the feedback.
Could you please test this build: https://drive.google.com/file/d/1DJDiGk_uMcYEHr-tK3SYRlhmlnntdpTN/view?usp=sharing
This release simply disables speed playback control.
For clarity sake, 6.0.77 has never been released to Google Play (only github).
I thought (and rechecked) that speed playback control was disabled in 6.0.80 with 1.0x playback speed but I might be wrong.
If 6.0.76 is ok and 6.0.77 not and the provided release above is ok. Then it means I still have playback speed code executed somehow and I need to remove this to stop stuttering.
Not explained yet: why it solves the stuttering for some.

**Comment by kparal** [comment] 2022-11-08 09:42
I figured out how to sideload apks on my TV. My results:
6.0.75 stutters
6.0.76 smooth
6.0.77 stutters
6.0.80 stutters
https://drive.google.com/file/d/1DJDiGk_uMcYEHr-tK3SYRlhmlnntdpTN/view?usp=sharing stutters

>  Not explained yet: why it solves the stuttering for some.

It might just be down to CPU speed 🫤

**Comment by courville** [comment] 2022-11-08 10:10
@kparal thanks for the summary. It helps. I do not believe in the CPU speed track.

**Comment by buthig666** [comment] 2022-11-08 10:15
Regarding Cpu speed: my Bravia Tvs, x950G and x85j, use the MediaTek 5893 and MediaTek 5895, respectively.  Don't know if that means much to anyone.  While I see dramatic stutter on the x950g I see subtle stutter on the x85j. (regarding the current v80 on playstore not the test build above in this thread.)

**Comment by courville** [comment] 2022-11-08 11:21
@buthig666 thanks for the support on this.
I have found one difference on codepath regarding AudioTrack buffer size and I would like to request feedback on the following build if this is not too much to ask https://drive.google.com/file/d/1cLKowsrSr30SLof53WVIViRm_LIm53Ls/view?usp=sharing
If this is not ok then I will redisable completely this playback speed which was not entirely eradicated to be sure this is it.

**Comment by courville** [comment] 2022-11-08 11:24
Playback speed eradicated build to be tested only after the previous one (pretty please) (should be like 6.0.76): https://drive.google.com/file/d/1K2nByWthfFprf4xSmLCb5fAANcNUjfC7/view?usp=sharing

**Comment by buthig666** [comment] 2022-11-08 11:25
Will do, will report back in 15-20 minutes or so... :)

**Comment by kparal** [comment] 2022-11-08 11:27
> https://drive.google.com/file/d/1cLKowsrSr30SLof53WVIViRm_LIm53Ls/view?usp=sharing

The playback seems smooth to me!

**Comment by buthig666** [comment] 2022-11-08 11:41
Ok sorry it's taking me a sec...  Literally a brand-new build and had to reset some smb settings on android.   The first file seems smooth (Ironically, I noticed the passthrough option is checked) I touched zero settings.  will try the second now.

**Comment by buthig666** [comment] 2022-11-08 11:53
So weird, the second one (something something no more) Seems to be smooth as well.  I don't know if that's any help I tested both on the Bravia that performs the worst.

**Comment by courville** [comment] 2022-11-08 11:57
If first build is smooth second one must be too.
Thanks a lot for your testing.
This means that in your particular situation, allocating 4x AudioTrack getMinBufferSize makes video stutter and 1x is ok.
I need to chew upon this discovery...

**Comment by courville** [comment] 2022-11-08 12:25
OK I found a discrepancy in the preload buffer size and buffer size in avos audiotrack code.
I am a bit doing some black magic there to align since I have no way to reproduce (I will ask the old guard about this behavior).
Could you check if this build meanwhile (pretty please again, when you get a chance): https://drive.google.com/file/d/1hXBat4cotfzZJev4y6nxYJfEj2mZKLFU/view?usp=sharing

**Comment by kparal** [comment] 2022-11-08 13:24
> https://drive.google.com/file/d/1hXBat4cotfzZJev4y6nxYJfEj2mZKLFU/view?usp=sharing

Stutters again.

**Comment by courville** [comment] 2022-11-08 20:46
FYI https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.81 released

**Comment by kparal** [comment] 2022-11-09 07:16
> FYI https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.81 released

Just to validate - a smooth playback.

**Comment by buthig666** [comment] 2022-11-09 07:55
Thumbs up!  Thanks so much for your hard work!

**Comment by courville** [comment] 2022-11-09 08:13
Let's close the issue for now.
TODO: put global experimental option for experimental playback speed.

**Closed as completed** 2022-11-09 08:13 UTC
Labels: bug, blocker

**Comment by courville** [comment] 2022-11-10 16:37
Note to self: issue happens on Mediatek CPUs (MT5891, MT9970B). Perhpas to reproduce on firetv dongle...
