### ISSUE TITLE
[Bug]: Multichannel AAC 5.1 no passthrough on FireTV devices.

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#825] opened 2023-02-10 00:13 UTC
### Problem description

Passthrough (option 2) has never worked for me (any version) on any FireTV devices with AAC 5.1 sound. Maybe I'm not understanding and this is not possible (except only if Nova would transcode to AC3 maybe?)

As an example that TV and receiver are capable of multichannel sound, Netflix app on FireCube 4K Gen2 does passthrough at least 5.1. This applies to movies encoded with AAC 5.1.

Fire TV device is connected directly to TV (Sony Bravia); TV then outputs SP/DIF via an optical cable to receiver. This setup is known to work as TV is capable of passing through multichannel PCM. This has been tested with the same Fire TV device and Netflix app. Works. Vimu Media Player also works, etc.

### Steps to reproduce the issue

Select Passthrough (Option 2). 

Play AAC 5.1 movie (any movie or TV show) = Not working. Only stereo 2.0 sound
Play AC3 5.1 movie (any movie or TV show) = Works. Multichannel 5.1 sound
Play EAC3 5.1 movie (any movie or TV show) = Works. Multichannel 5.1 sound

Have tested with Option 1 and same problem.

I know it's different, but AppleTV HD connected the same way (direct to TV, TV via optical to receiver) can play AAC5.1 (Infuse app).

### Expected behavior

AAC 5.1 should output multichannel sound like AC3 and E-AC3.

### Your phone/tablet/androidTV model

Fire Cube 4K 2nd Gen

### Operating system version

Fire OS 7.6.2.4

### Application version and app store

v6.0.95 and below

### Additional system information

Fire TV device is connected directly to TV (Sony Bravia); TV then outputs SP/DIF via an optical cable to receiver. This setup is known to work as TV is capable of passing through multichannel PCM. This has been tested with the same Fire TV device and Netflix app. Works. Vimu Media Player also works, etc. AC3 5.1 and EAC3 5.1 works, so TV and receiver setup via optical is capable and works.

**Comment by phhusson** [comment] 2023-02-10 19:39
SPDIF can't passthrough PCM 5.1.
You say you tested with Netflix, but Netflix outputs EAC3 not AAC or PCM.

Do you confirm that you have one app that works on FireTV that can output PCM 5.1? (I'm not speaking of Kodi's transcoding feature)
Please provide the result of `adb shell dumpsys media.audio_policy`

**Comment by ghost** [comment] 2023-02-12 14:58
You're absolutely right. This should be a feature request ("Transcode AAC into AC3 option") instead of a bug report. I gravitate toward AppletTV + Infuse for this one feature alone. Please close as this is not a bug.

**Comment by phhusson** [comment] 2023-02-12 15:03
Dupe of https://github.com/nova-video-player/aos-AVP/issues/430

**Closed as completed by phhusson** 2023-02-12 15:03 UTC
Labels: bug
