### ISSUE TITLE
希望webdav支持

### ISSUE THREAD

**Issue by yuanwenbing** [nova-video-player/aos-AVP#799] opened 2023-01-06 08:13 UTC
### Description

希望webdav支持，特别喜欢这个播放器。界面特别舒服，但特别需要webdav

**Comment by wowdd1** [comment] 2023-01-07 03:49
+1

**Comment by mjnewton** [comment] 2023-01-07 13:15
Is this a duplicate of https://github.com/nova-video-player/aos-AVP/issues/761?

**Comment by InitialXKO** [comment] 2023-01-07 14:29
> 

It's obvious, what an essential feature forgotten.

**Closed as completed** 2023-01-08 14:39 UTC
Labels: duplicate, enhancement
