### ISSUE TITLE
Arm cortex a55 cant install arm64-v8 apk

### ISSUE THREAD

**Issue by shanestonk** [nova-video-player/aos-AVP#681] opened 2022-07-19 14:19 UTC
I think there a bug because i cant install the arm64-v8-api-21+.apk on my arm cortex a55. But when i tried the armeabi.apk it can be installed.

https://developer.arm.com/Processors/Cortex-A55

https://www.cnx-software.com/2022/02/04/amlogic-s905c2-quad-core-cortex-a55-processor-digital-tv-tuners-cas/

Amlogic S905C2 preliminary specifications:

CPU – Quad-core Cortex-A55 up to 2.0 GHz
GPU – Arm Mali-G31MP2 with support for OpenGL ES 3.2, Vulkan 1.0/1.1, and OpenCL 2.0

Video
Decoding – AV1 up to 4Kp120, 10-bit H.265, VP9, AVS2 up to 4Kp75, H.264 4Kp30
Encoding – 1080p60 H.265/H.264
HDR – HLG/HDR10/ 10+ Dolby vision, TCH PRIME

Architecture | Armv8-A (Harvard)

Extensions | Armv8.1 extensionsArmv8.2 extensionsCryptography extensionsRAS extensionsArmv8.3 (LDAPR instructions only)

ISA support | A64, A32, and T32 instruction sets

The reason i want to install the arm65-v8a because i cant play av1 2160p video with nova armeabi apk. My processor support hardware decode av1 4kp120.

the android box default media player can play the 2160p av1 video but nova cant play av1 2160p.

**Comment by shanestonk** [comment] 2022-07-20 09:01
https://issuetracker.google.com/issues/37134362?pli=1

**Comment by phhusson** [comment] 2022-07-20 09:08
> The reason i want to install the arm65-v8a because i cant play av1 2160p video with nova armeabi apk. My processor support hardware decode av1 4kp120.

Open a ticket with this issue. It is not related to with arm64-v8.

Closing as a duplicate of #683

**Closed as completed by phhusson** 2022-07-20 09:08 UTC
