### ISSUE TITLE
External player issue

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#106] opened 2019-04-14 21:05 UTC
Hello
As playback is not smooth yet I decided to setup MXPlayer as my external player in NOVA, unfortunately it does not display the subtitle files.
If I open MXPlayer from ES File Explrer it works.
What could be the reason for that?

**Comment by courville** [comment] 2019-05-28 20:11
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/140

**Closed as completed by courville** 2019-05-28 20:11 UTC
