### ISSUE TITLE
App crash on launch

### ISSUE THREAD

**Issue by Ionaru** [nova-video-player/aos-AVP#454] opened 2021-07-06 01:26 UTC
Since a few weeks I am no longer able to open Nova Video Player on my phone. When I open the app, it shows the blue app background and then returns me to my home screen, the app is then also removed from the running apps.
I believe some issue is causing the app to crash on launch.

I've tried a few things to try and get the app to work, but no luck

- Reinstalled from Google Play.
- Toggled app permissions.
- Cleared app cache and data.
- Ran without network connectivity.
- Installed an older 5.x version from APK.
- Installed a 6.x beta version from APK.

At this point I've ran out of things to try, what can I do to get the app to work?

Phone info:
Honor 9, STF-L09
EMUI 9.1.0, Android 9

**Comment by courville** [comment] 2021-07-07 09:40
Hi, what would be helpful is to get some logs (adb logcat) of the crash since I am not able to reproduce.
Could you please check if you can get these following https://github.com/nova-video-player/aos-AVP/wiki/Debugging ?
Thank you

**Comment by Ionaru** [comment] 2021-07-07 22:06
Here are my log files, they are the recording of me trying to open the app through the default EMUI launcher.
The `nova_only.txt` files is all lines filtered by `org.courville.nova`, the other file is unfiltered.
I hope this helps.

[nova_only.txt](https://github.com/nova-video-player/aos-AVP/files/6780279/nova_only.txt)
[full_log.txt](https://github.com/nova-video-player/aos-AVP/files/6780280/full_log.txt)

Using Windows so I installed Android Studio and used its logcat feature with my phone connected to the PC.

The `/storage/emulated/0/Download/org.courville.nova//nova.log` file the log refers to is completely empty (0 bytes).

**Comment by courville** [comment] 2021-07-09 08:01
There is unfortunately nothing noticeable in the logs.
Have you tried to reboot your phone?
There has been cases of this "stuck on blue screen issue" that was resolved by a reboot.

**Comment by courville** [comment] 2021-07-09 08:46
Before you reboot, I could send you a debug apk to trace where the application is stuck using a debugger if you are ok to proceed with this.

**Comment by Ionaru** [comment] 2021-07-09 21:41
I rebooted my phone and that seems to have fixed the issue.

**Comment by courville** [comment] 2021-07-18 16:24
Good to know. I should find a way to debug this one since after some time it happens. Not clear if it a real nova issue though. Will reopen when I reproduce with a debug apk.

**Closed as completed by courville** 2021-07-18 16:24 UTC
