### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by nxjonson** [nova-video-player/aos-AVP#881] opened 2023-04-23 06:28 UTC
### Description

I want to add the function of skipping titles and credits.

**Comment by courville** [comment] 2023-05-09 06:29
I think this is a duplicate of https://github.com/nova-video-player/aos-AVP/issues/610
Indeed a nice feature to add.
If you want to contribute you are welcome.

**Comment by courville** [comment] 2023-05-09 06:30
I will close the issue and let's follow in the earlier one.

**Closed as completed by courville** 2023-05-09 06:30 UTC
Labels: duplicate, enhancement
