### ISSUE TITLE
[Bug]: Not getting movie posters on get info

### ISSUE THREAD

**Issue by petar-cvit** [nova-video-player/aos-AVP#1154] opened 2024-03-13 11:24 UTC
### Problem description

When trying to `get info` for a movie, I don't get movie posters. Other parts of the info seem to be loaded, but movie posters are not loaded.

Its much easier picking a movie with displayed posters.

### Steps to reproduce the issue

Select a movie, delete the current info from it and hit `get info`. You should see multiple infos you can choose from which were scraped, but none of those have posters.

### Expected behavior

I would expect that the movie poster will be loaded alongside other info data.

### Your phone/tablet/androidTV model

Q10 PRo

### Operating system version

Android 7

### Application version and app store

v6.2.57 from Google Play store

**Comment by courville** [comment] 2024-03-18 21:31
Thanks for reporting the issue. Unfortunately, I do not reproduce on android tv and phones that I own at least with latest github release.

**Comment by L3deni** [comment] 2024-03-20 15:48
I have been using the program since the beginning and have never had any problems. For a week now I have also had the problem that no covers are displayed. I've already tried uninstalling and reinstalling the app. Now only 10% of the covers are displayed.
My TV is a Sony X9405C with AndroidTV an v6.2.57

![20240320_164107~2](https://github.com/nova-video-player/aos-AVP/assets/164203166/698f87ec-a83b-4a9a-a1be-d18e06d3c61b)
![20240320_164158~2](https://github.com/nova-video-player/aos-AVP/assets/164203166/a3688cf3-f862-4022-bfb8-01b8340ba314)
![20240320_164212~2](https://github.com/nova-video-player/aos-AVP/assets/164203166/5b0e7fab-2a2d-4f0c-8842-d9772431dd0c)

**Comment by courville** [comment] 2024-03-20 20:24
@L3deni, where are your files located? Could you please check that you are able to open themoviedb from available movie poster/description?

**Comment by L3deni** [comment] 2024-03-21 17:10
@courville My files are unchanged on my NAS and I access them via SMB.
All posters and backgrounds are available on the themoviedb website. If we stay with Conan (1982) as an example.
![Background](https://github.com/nova-video-player/aos-AVP/assets/164203166/9f408fc6-4b38-4c73-ba35-55ee65187950)
![Cover](https://github.com/nova-video-player/aos-AVP/assets/164203166/97f5205b-387b-4638-877c-9c4667e6ade2)

**Comment by yaoyao5128** [comment] 2024-04-11 16:41
I'm having the same issue

**Comment by courville** [comment] 2024-04-11 18:21
Let me guess you are located in India?

Cf. https://www.reddit.com/r/NovaVideoPlayer/comments/1beft2v/information_tmdb_is_not_accessible_in_india/

This could be the reason why nova is not able to scape correctly video descriptions.

To be more constructive, perhaps use https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone on your android tv to go around the restrictions.

**Comment by L3deni** [comment] 2024-04-13 08:07
@courville I did a few more tests. I have manually installed v6.2.67 on my Sony X9405C. Unfortunately, I still don't see any posters.
It's even worse with the latest version. Previously, some posters were displayed because there were still Archos files in the same folder. Now these are no longer recognized either.  Maybe this will help you to solve the problem?
![Example](https://github.com/nova-video-player/aos-AVP/assets/164203166/e05b825c-1815-4ea5-9093-0fb0dc82d718)

**Comment by courville** [comment] 2024-04-13 13:28
@L3deni thanks for sharing more information.
Please try to delete all `*.archos.nfo` and `*.archos.jpg` files and remove from nova settings the processing of NFO files just to check if it any better (try first in one directory).
You will need to rescrape manually the file.

**Comment by Larfel4Novaonly** [comment] 2024-04-15 00:19
Thanks for continued help. Sorry I did not respond yesterday. I was working all day on testing to figure it out. No luck.  When I check the USB external on the computer, I see and have deleted the courville app data and cache folders, all though they are always empty anyway. (same with any leftover archos folders.) Loading the USB back to TV rescans the movies and TV shows, but same behavior, no posters or backdrops.
 
I added some more screenshots of my TV screen here for more context.
TMDB website on TV Android browser (Firefox) shows all images. But the "Nova Video WebView TMDB" button link on the Nova app does not. Nova loads the website fine but images remain broken. This must be the crux of the problem. Are there any scripts or Java updates that Nova changed to prevent images from loading on IT'S TMDB link? It's so frustrating. What could be preventing the Nova TMDB link from loading (thus accessing and downloading posters and backdrops) images? 

Also, there ARE no archos.nfo or archos.jpg files on the USB drive or the internal Android found.  The nova data and cache folders are there, but they are empty. the nova TMDB link to get posters or backdrops does not work properly is seems to focus on?
I'll look for your next suggestions. 
Thanks!
![Nova TMDB webview NOT ok 20240413_174724](https://github.com/nova-video-player/aos-AVP/assets/166771375/02d0c03d-f46b-4371-8740-db40790d2c90)
![Nova TMDB webview NOT ok 20240413_174937](https://github.com/nova-video-player/aos-AVP/assets/166771375/325ab8c0-42e2-4faa-8984-00c5d9bb8bbe)
![Nova TMDB webview NOT ok 20240413_174954](https://github.com/nova-video-player/aos-AVP/assets/166771375/969f2294-8e63-4321-8a2b-d71f9c232e88)
![Nova TMDB webview NOT ok 20240413_175220](https://github.com/nova-video-player/aos-AVP/assets/166771375/0d19d085-af0c-470d-8fb4-b91c1b0dc2ec)

**Comment by courville** [comment] 2024-04-15 06:24
@Larfel4Novaonly thanks for the thorough report and testing. Would you be able to install on your TV a custom apk and take adb logcat logs? I can add some meaningful logs to see why nova only cannot access tmdb posters...

EDIT: FTR I tried on a sony android TV and I can get tmdb posters. We have to understand what is different in your case

**Comment by Larfel4Novaonly** [comment] 2024-04-16 00:30
Yes for sure! I've tried again today to reinstall NOVA (after deleting all
remnants of caches and data files etc. for them) and nothing changed.
Please send the TV custom apk to test and diagnose and how to send some
logs to you. I trust you. Awaiting your reply.  I Really want to make this
work!  Thank you so much for your help!

**Comment by Larfel4Novaonly** [comment] 2024-04-16 20:11
Hi again, I hope I understood you. Are you sending me the  "TV custom apk to take adb logcat logs"? I sure don't know how without this.  Thanks!

**Comment by Larfel4Novaonly** [comment] 2024-04-16 20:17
Hi,    Still waiting for you to send the apk to me for "TV a custom apk to
take adb logcat logs" from you so you can diagnose the problem. As soon as
you send that I'll send you back what you need.  Any idea when you'll have
the time to send that? Thank you again.

**Comment by Larfel4Novaonly** [comment] 2024-04-16 23:42
Hi,  Still waiting for your TV custom apk you suggested to send me to
perform what you ask for logs to send you for diagnosis. Just wanted to
make sure you've got this request, don't mean to keep asking.  When you
send me the program and you tell me how to extract the information you need
with it I will do it immediately. I'm so appreciative of your assistance in
figuring out this NOVA image problem!  Thank you. standing by....

**Comment by courville** [comment] 2024-04-17 09:07
Please use the following apk https://drive.google.com/file/d/1EYLQV4bYrbf0l2r0ZEKa3E7Psl3glpOj/view?usp=sharing that contains scraper logs (remove video info on a file and request it through nova UI to check if it gets all the expected information: need okhttp.OkHttpClient and all scraper logs).

**Comment by Larfel4Novaonly** [comment] 2024-04-17 19:20
Okay! Thanks! I'll work on it today and let you know right away. Hope I can make the program work and give you what you need. I'm pretty good at stuff like this, but have never done this before.

**Comment by courville** [comment] 2024-04-17 20:16
Please have a look at https://github.com/nova-video-player/aos-AVP/wiki/Debugging and if you need help let me know.

**Comment by Larfel4Novaonly** [comment] 2024-04-17 23:55
I definitely need your help! Been trying for hours now. The apk you sent just seems like the normal NOVA app, albeit a newer date. It has same Identical behavior with no images loading. My Sony TV has ADB debugging enabled in developer options, I checked it before and re-verified now.            But I don't understand the rest of the wiki debugging link you sent. Something about a debug host?, installing two More applications?, etc..
    I know the IP address of my Sony Android TV. But that's as far as I can understand. How can I access the logs and files you need on the TV?   Thanks so much for a walk through. I'm sure trying.

**Comment by Larfel4Novaonly** [comment] 2024-04-18 00:27
Update, I downloaded and installed Android SDK on my windows 10 computer. But that's as far as I can go. I tried to open those files but nothing happens. I am unable to do anything else without your help. On standby until further instructions. 

P.S. Sure thought it would be easy to send simple logs to you! Can't NOVA itself on the Android TV extract the logs you need and put them on a folder that I can download to a USB flash then send it to you here? I'm sorry I'm so ignorant.

**Comment by L3deni** [comment] 2024-04-18 17:09
@courville I installed your APK and make a dump of the Nova media database
[org.courville.nova-media.zip](https://github.com/nova-video-player/aos-AVP/files/15028156/org.courville.nova-media.zip)

**Comment by courville** [comment] 2024-04-18 17:11
@L3deni, thanks this is progress. What I would need instad of the media database dump (which I will analyze) would be an `adb logcat` when doing the scrape of a video (getting the info).

**Comment by courville** [comment] 2024-04-18 17:17
oh in your database there is literally no multimedia files. It is basically empty. This means that there is no import from your USB storage and hence no scanning.
Nova relies on the fact that Android from your sony TV indexes via its database the content of the storage attached.
Then nova imports what Android framework sees as multimedia files.
There Android says to nova: nothing to report.
This must be the issue.
Is there an android option to scan usb storage on your TV?

**Comment by courville** [comment] 2024-04-18 17:18
Only file it sees is the SMB share from your synology NAS (which is relying on nova scan and not android one).

**Comment by L3deni** [comment] 2024-04-18 19:18
@courville 
(i) How can i give you the adb logcat?
(ii) Thats correct my files are on the nas
(iii) Yes i deleted Fileinfo and rescan manualy. I did it only with 1 File

Would it help if i put some videos on a usb stick? Should i add an directory from my NAS to nova?

**Comment by courville** [comment] 2024-04-18 20:17
For adb logcat you need to adb connect to your device following https://github.com/nova-video-player/aos-AVP/wiki/Debugging or internet howtos.
What I see from the db is that Akira on the NAS is scraped correctly (info retreived), backdrop url is correct https://image.tmdb.org/t/p/w1280/jmlM5sa8vrBWHSBubqAithX6Fx5.jpg that is referenced as saved here on your device /data/user/0/org.courville.nova/app_scraper_backdrops/633210381138932556l.jpg, however poster url and file are NULL i.e. empty and this is not good. We need the logcat logs to see why the file is not retreived and saved.
It should not happen.

**Comment by Larfel4Novaonly** [comment] 2024-04-18 20:23
Hi, Still haven't had a response from you for getting logs you wanted for NOVA images not showing. 
Somehow another person in this thread has joined with a different issue?  
I keep checking for your help to get the files you need to fix NOVA's problem. Please check my messages above if you need to refresh.  I have no idea how to get what you require. I've tried everything so await your instructions to perform.  Standing by more....  Thanks so much!

> Please have a look at https://github.com/nova-video-player/aos-AVP/wiki/Debugging and if you need help let me know.  (another try at letting your know from couple of messages, most definitely need your help. I tried what I could from the link you sent but nothing worked.

**Comment by courville** [comment] 2024-04-18 20:31
@Larfel4Novaonly sorry, trying to answer to two persons at the same time indeed.
On your case, you need to identify as described in first section of https://github.com/nova-video-player/aos-AVP/wiki/Debugging the IP of your android TV. Then you `adb connect IPADDRESS` to the android tv. Then you `adb install file.apk` to the TV from the terminal on your PC.
Afterwards you will be able to do the scrape and send me while doing an file info and indexing the result of the `adb logcat` from your PC (it can be long output). If my explanation is not enough please google it, there are plenty of good tutorials.

**Comment by Larfel4Novaonly** [comment] 2024-04-18 20:55
Okay got the confusion. That explains it. You are doing fine, has to be hard juggling issues and people.    
  I've been trying but still no success. My windows computer shows the TV on the network and the TV's IP address. I open CMD on windows and did what you said yesterday, and now.      (Sony TV is on, Developers USB debugging enable)   
'adb' is not recognized as an internal or external command,
operable program or batch file."   This command does not work. What is wrong? Very frustrating. I attached to screenshots, one of windows network showing Sony TV IP and other CMD not accept adb command. 
  Your instructions seem simple. But it fails.  What next.  Thanks!



P.S. I Googled all help. no good. can't figure out problem. tried many attempts. too many results, but none are correct and don't work when I try them. makes no sense. Please see what I can try now.... thank you

**Comment by Larfel4Novaonly** [comment] 2024-04-18 23:54
Just another update.  Trying to follow the ADB debugging link you sent. I found and installed Android Studio with sdk platform tools on my Windows computer.  Very large application (almost 2GB) and lot's of installing. (very reluctant to do this but seems? what the instructions said) Then Again, tried adminis. command prompt "adb connect". After all that, STILL same result as my above  reply said. Did not work.       I give up on my own.  I absolutely need your help to continue.    What is the Easiest way to get you the logs from NOVA from my TV. Can I uninstall Android Studio?  Am such at a loss.

**Comment by Larfel4Novaonly** [comment] 2024-04-19 04:22
update, 4 more hours into it today must stop and wait for advice from you, I'm exhausted. But after intense reading I was able to create a path for adb bugging, but cannot get any further. at least CMD accepts and recognizes adb command now.      screenshot attached to point of can't get further.    Hope you can direct me to next step and exactly how to extract the logs you need from NOVA. Look to hear back for what to do next.


Here is final screenshot today of fail to "adb install file.apk" that you wrote to do. Learning alot but don't know how to do the rest of this. (drag and drop into CMD window the  nova apk you sent failed also.) I must be doing something obviously stupid but am at a complete loss.         Thank you so much!!

**Comment by courville** [comment] 2024-04-19 05:10
OK I am able to reproduce the issue on old Android version (API21 and perhaps later). Images fail to download with:
```
Exception: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```
I will investigate no need to dig further on your side for now.

**Comment by yaoyao5128** [comment] 2024-04-19 05:18
I did that. Here are the logcat & nova-media_db. I hope it can be usefull.

**Comment by courville** [comment] 2024-04-19 18:27
OK I think I have a solution. It turns out that on old android versions (<7.0), nova code relies on android platform certificates to check https connections and since the CA are out of date, it fails on image.tmdb.org.
Github release v6.2.69 https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.69 addresses this issue: please try it out and report if it solves it on your end.

**Comment by Larfel4Novaonly** [comment] 2024-04-19 20:18
Okay tested v6.2.69 completely. I think you are on the right track, BUT it still does not work correctly. (to be sure my Sony Android TV version shows 7.0, not <7.0 if that helps at all.)   A couple of posters and backdrops loaded. Most of them did not, and still have the blank tiles. And using the NOVA Video WebView "TMDB" button on each movie or TV show STILL has all broken image icons on them. So no images are still showing on the TMDB link website (broken image icons as before), and say 1 or 2 images out of 10 or 12 "tiles" for posters or backdrops generated images on the NOVA description page, the remainder, about 95% still not shown and are blank tiles in the poster/backdrop rows.    
   So the good thing, I think, is that you are on the right path, but still not working as should.  Please work on the android platform certificates angle? more and send out another updated NOVA version. Summed up, better but still definitely broken on my end.  I attached some screenshots to show.   Thank you so much for your continued support!
![20240419_130607](https://github.com/nova-video-player/aos-AVP/assets/166771375/a6a78a62-afb1-41ed-851f-152735f59798)
![20240419_130052](https://github.com/nova-video-player/aos-AVP/assets/166771375/7389dea1-9f06-4984-8a76-d011bbcebef7)
![20240419_130142](https://github.com/nova-video-player/aos-AVP/assets/166771375/287cc3d9-4138-48cd-84de-944930bf13ef)
![20240419_130250](https://github.com/nova-video-player/aos-AVP/assets/166771375/ceff607b-6cc9-4ff2-b812-2e3a380fe26b)

P.S. Still have been unable to figure logs procedure as stuck on the "install file .apk" part that you said. It keeps failing. So I can't  send you them yet until you walk me through the remainder of the tasks. Please inform to send you specific logs that should isolate the issue for you to resolve.     But... if you can follow the direction you just tried on  v6.2.69 it just might be the ticket to work!!     I'll look for either responses from you to know what to do next.

**Comment by courville** [comment] 2024-04-19 20:29
@Larfel4Novaonly, my fix does not apply to the webview for TMDB link: it should apply only on the poster retrieval.
Do you confirm that you have uninstalled/wiped out nova cache before rescrape of your video collection?

**Comment by Larfel4Novaonly** [comment] 2024-04-19 20:54
Yes, Completely uninstalled and wiped out nova cache and data files and rescraped all videos. did not help. also, Initially a few weeks ago in some older NOVA iteration, TMDB site accessed from nova webview DID show all images on their site from within the NOVA app. I remember was even able to ADD some poster and backdrop images from it! So it seemed to work at one time. None of that works now since the current issue.

**Comment by yaoyao5128** [comment] 2024-04-20 02:48
I installed v6.2.69. Found two that still have issues.
1.org.courville.nova/com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingActivity
2.org.courville.nova/com.archos.mediacenter.video.leanback.settings.VideoSettingsActivity
![20240420102519](https://github.com/nova-video-player/aos-AVP/assets/31963173/4efefa44-430b-4a34-909e-d23757998d82)
![20240420103512](https://github.com/nova-video-player/aos-AVP/assets/31963173/f5958b5c-a516-41e8-9877-0752e459af96)

**Comment by courville** [comment] 2024-04-20 08:17
@yaoyao5128 what Android version are you using?
Nova uses the Android system webview: in your case it means that trakt site is rejecting your Android device webview version.
I will check if I can workaround `ManualShowScrappingActivity` not using your Android device platform certificates.
At this point I believe this is not nova's fault but simply that your Android device is not maintained by its OEM providing firmware updates (i.e. too old).
I might declare nova not compatible with these versions of Android in the future to avoid people complaining on nova while in reality it is Android firmware obsolescense we are discussing in this issue thread.
I can continue adding band aids here and there but it is not sustainable sorry.
This is indeed sad.

**Comment by Vogeleijoll** [comment] 2024-04-20 10:12
Hello,
First of all, many thanks to the administrator for the great work. I also have the problem with the old software.
My improvised solution is this:
I have installed the app on a current Android. Posters and information were also found. Check the box on Export Files in the settings. On the Android 7 device, check the box for Process info files locally. The posters are already there.
Hope this helps some.

**Comment by courville** [comment] 2024-04-20 11:06
Note for the explanation, image.tmdb.org uses letsencrypt:
```
echo | openssl s_client -connect image.tmdb.org:443 -servername image.tmdb.org 2>/dev/null | openssl x509 -noout -issuer -dates -subject | grep -i "issuer\|subject"
issuer=C=US, O=Let's Encrypt, CN=R3
subject=CN=image.tmdb.org
```
And letsencrypt does not support Android 7 and below: cf. https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686 and cf. https://scotthelme.co.uk/lets-encrypt-old-root-expiration/
DST Root CA X3 expired on September 30, 2021.
This means that every site that uses this CA that nova will attempt to access using the Android device CA certificates will fail.
Funny part is that api.themoviedb.org still works because it does not use letsencrypt:
```
echo | openssl s_client -connect api.themoviedb.org:443 -servername api.themoviedb.org 2>/dev/null | openssl x509 -noout -issuer -dates -subject | grep -i "issuer\|subject"
issuer=C=US, O=Amazon, CN=Amazon RSA 2048 M03
subject=CN=*.themoviedb.org
````
Which results in getting the video file info and not the posters/banners...

**Comment by yaoyao5128** [comment] 2024-04-20 15:21
> @yaoyao5128 what Android version are you using? Nova uses the Android system webview: in your case it means that trakt site is rejecting your Android device webview version. I will check if I can workaround `ManualShowScrappingActivity` not using your Android device platform certificates. At this point I believe this is not nova's fault but simply that your Android device is not maintained by its OEM providing firmware updates (i.e. too old). I might declare nova not compatible with these versions of Android in the future to avoid people complaining on nova while in reality it is Android firmware obsolescense we are discussing in this issue thread. I can continue adding band aids here and there but it is not sustainable sorry. This is indeed sad.

My TV is Xiaomi4A on Android 6.0.1. And now I know the cause of this problem. It's really a sad news. BTW, nova is great app. Thank you.

**Comment by Larfel4Novaonly** [comment] 2024-04-20 20:18
I don't use Trakt but still need NOVA to be able to extract and export and view the posters and backdrops from the TMDB site it connects to within the app. I can't upgrade above the current Android 7 on my Sony TV. 
 PLEASE continue to try to patch, to update or dismiss Android device platform certificates for your app to allow it to work again. I use NOVA all the time and it's been the best there is. Thank you so much for your effort and time doing this! I really appreciate your work. I will look and hope for the next iteration to fix this as soon as you can.

**Comment by Larfel4Novaonly** [comment] 2024-04-21 00:38
Found a behavior that may be a clue to help you, help me, and others! (w/ current v6.2.69). We know that for some reason TMDB images don't show currently on NOVA's TMBD webview link, broken image icons. At least with Android 7 for sure. (Possible Android certificate issues, needing updated or renewed, so far...) We know that the movie or TV, NOVA page, does show empty black tiles in rows for posters and backdrops, but with the 2 triangles icon on the tiles and designating no images. That implies that NOVA created, detected something, (found an image file?) but only put an empty tile placeholder in the row but nothing it on it.        I clicked on a "blank tile" (poster and/or backdrops) to change one. Nothing appeared to happen. I then backed out of movie page to home page (exited that screen). Went back in, and that ONE poster or backdrop image was there!, and could be selected.  I repeated all: clicked/chose, moved to next blank tile in line, selected that, with every single blank tile in the poster and backdrop rows. Again, nothing seemed to change. Still could not see a preview of any poster or backdrop image. Took quite some time to select each individual say 30 blank poster tiles, and many blank backdrop tiles. Backed out again to home page. Went back into the movie, and every poster and backdrop image preview were there to see and you could choose them!! You had to Manually (blindly) select every individual blank tile, back out and come back in to see them and what's available.  
That has to be something to direct you to repair. It's one step closer to working!    Try on a system you see the issue with and let me know if you can fix that. There has to be a work around.  Thanks! I'm working hard on my end also to get NOVA working again as it did before.

**Comment by yaoyao5128** [comment] 2024-04-21 08:26
Latest situation:
With 6.2.69, I can download posters from TMDB but not preview posters when retrieval.
I updated Android system webview manually. Now I can link to trakt.tv again.
Thank you for your efforts！

**Comment by courville** [comment] 2024-04-21 16:32
> With 6.2.69, I can download posters from TMDB but not preview posters when retrieval.

this is still a mystery to me since it works on more recent versions of Android but not old ones even if the poster from imdb is downloaded. I will investigate this part.

**Comment by courville** [comment] 2024-04-21 16:34
@Larfel4Novaonly, I think the TMDB poster download is now working but you get the same symptom as @yaoyao5128 triggered another way. I will investigate.

**Comment by Larfel4Novaonly** [comment] 2024-04-21 23:34
Fascinating. Will look for your next iteration. Really appreciate your help and expertise. Each behavior is slightly different but similar and tells me you are on the correct track in some form and that you may be very close. Yes! keep trying.  Thank you!!!

**Comment by L3deni** [comment] 2024-04-22 16:52
@courville 
v.6.2.69 is so much better, thank you very much.
I now have 1 poster and 1 background image everywhere, which is great. I still don't see the other posters and wallpapers, but better than nothing.
![test](https://github.com/nova-video-player/aos-AVP/assets/164203166/068bcd2e-db19-4750-a7fa-cd774257f7c5)

Here is my media database File
[org.courville.nova-media.zip](https://github.com/nova-video-player/aos-AVP/files/15066091/org.courville.nova-media.zip)

**Comment by Larfel4Novaonly** [comment] 2024-04-25 18:33
Hello, Checking in. How is your progress in fixing NOVA not getting poster or backdrop images on the movie or tv page? (Android 7) Been checking a lot each day to see when you'll find and send a solution. Really want to start using NOVA again.  Thank you!

**Comment by courville** [comment] 2024-04-27 15:00
Here we go again. Could you please try this pre-release to see if it fixes the issues on your end: https://drive.google.com/file/d/1OJfw7bbYp9muUPg2i7dOxeLH0kCITqor/view?usp=sharing
Turns out that the posters/backdrops are also downloaded through Picasso library that must be made aware of the correct letsencrypt certs on Android versions below or equal to 7.1.

If you are happy with nova please support our work.

**Comment by Vogeleijoll** [comment] 2024-04-27 17:56
It is work on Android 7. Great Shop. Thank you

**Comment by Larfel4Novaonly** [comment] 2024-04-29 04:09
Hello, I so appreciate your time and work.     However, your latest change above broke all "Trailers". Now THEY show a blank tile, where as they did not Ever before this last iteration of 4/27/24.  Something that you did that enabled posters, also "Disabled Trailers" now, on All movies and TV shows at the same time.        If you fix that, I would gladly and fully support you and NOVA for all your effort.  It's almost back to how it worked in the beginning of this.  

  Please make the Trailer tiles work back again and not show blank tiles.  Thank you very much!  I'll look for your fix, it should be the last repair that needs to be done to have NOVA behave as it did before.

**Comment by yaoyao5128** [comment] 2024-04-29 06:26
In v6.2.70, there is also a legacy issue about certificates, when viewing the TMDB website in nova, the pictures cannot be displayed.

**Comment by courville** [comment] 2024-04-29 10:24
For trailers, perhaps only letsencrypt certificates are trusted and not platform ones additionally. I will check.
For TMDB website in nova it might be the webview that is KO. I will try to reproduce but perhaps it is external to nova.

**Comment by yaoyao5128** [comment] 2024-04-29 12:39
In order to verify that the webview can display the TMDB properly, I installed the "emotn browser" on my TV, and it can display the TMDB website normally. 
Images comparison:
In nova:
![20240429201440](https://github.com/nova-video-player/aos-AVP/assets/31963173/4f9e0831-242d-483d-9036-b36a4d3f6064)
In browser:
![20240429201938](https://github.com/nova-video-player/aos-AVP/assets/31963173/155b6a7a-3695-408f-b3bb-005a086c0eac)
Another minor issuse: 
The ”movies thumbnail“&“TV shows thumbnail” are not displayed correctly when cold starting nova.
This issue seems to be with v6.2.69 and v6.2.70 .
Cold start nova:
![20240429202216](https://github.com/nova-video-player/aos-AVP/assets/31963173/bddae9d6-6fd1-490d-9645-81ce8d48a7f6)
Hot start nova:
![20240429204146](https://github.com/nova-video-player/aos-AVP/assets/31963173/6b6f86fe-93f5-4a8c-963c-a351302584e7)

**Comment by courville** [comment] 2024-04-29 13:51
@yaoyao5128 you cannot compare with a browser that would embed all the certificates.

**Comment by Larfel4Novaonly** [comment] 2024-04-30 00:54
Still no Trailer images now on v6.2.70 for movies or TV shows. Please check. (attached an example) They were there on 4/19/24 iteration and all versions before but something broke it after that version.  Please continue to fix. Thank you so much!           
  (TMDB Nova webview images came back on 6.2.69 if that helps any.)


![20240429_173051](https://github.com/nova-video-player/aos-AVP/assets/166771375/deb27789-a21a-4530-8db4-763ecc169118)

**Comment by Larfel4Novaonly** [comment] 2024-04-30 00:55
![20240429_173006](https://github.com/nova-video-player/aos-AVP/assets/166771375/30a67190-6c3a-4345-8ee6-31eda8b064f2)

**Comment by courville** [comment] 2024-04-30 10:52
@Larfel4Novaonly I fixed it yesterday and will provide a release soon for you to test.

Regarding webviews, it will not be fixed because it is not nova related but platform related.

**Comment by Larfel4Novaonly** [comment] 2024-04-30 19:36
Thank you so much! Your time in this is very appreciated. Look forward to testing it as soon as you send it.        Not sure if you understood my last post, but I mentioned that TMDB NOVA Video webviews DO work and show images now since your latest release. Whether inadvertently or not, you fixed that part!   Thanks for reminding me that that area is platform related, but it does work currently, so no problem there; (until Android breaks it again!)   Standing by for fixed release!

**Comment by Larfel4Novaonly** [comment] 2024-05-02 21:11
Hello,  Will you be able to send the new release that you fixed a few days ago soon? I'm anxious to have it working again. Thank you very much.

**Comment by courville** [comment] 2024-05-03 06:04
@Larfel4Novaonly please try https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.70

**Comment by Larfel4Novaonly** [comment] 2024-05-03 20:56
Hello,  You sent the wrong one. This is the same version that did not work.  I tried this one all over again but same issue of course. You can check the posts above and attachments. ("org.courville.nova-2594832-6.2.70-20240428.1407-armeabi-v7a-release" was the same version link from last week that was broken) Still No Trailers are showing. Could you please send the one you mentioned you fixed a couple of days ago?  Thank you very much. Please send the repaired one as soon as you can.

**Comment by courville** [comment] 2024-05-04 08:20
You are right, this one does not have the latest patch. Here you go: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.71

**Comment by L3deni** [comment] 2024-05-07 10:00
@Larfel4Novaonly Have you tested v6.2.71?

**Comment by courville** [comment] 2024-05-09 11:42
Should be fixed, please reopen if not.

**Closed as completed by courville** 2024-05-09 11:42 UTC
Labels: bug

**Comment by L3deni** [comment] 2024-05-09 19:43
@courville yes, with v6.2.70 everything works perfect now. Thank you!!!

**Comment by Larfel4Novaonly** [comment] 2024-05-10 01:07
Hello, Very sorry had emergency and couldn't test sooner.  Yes "v6.2.71" works now again on Android 7.0! (v6.2.7.0 did Not). Everything appears to be functioning normally again as it did a few weeks ago before the apparently Android certificates went astray. You are a genius. Thank you for all your time and hard work. Let's hope it lasts, until Android changes or things expire again. NOVA again, is now the best player out there and has regained it's title! Much thanks!
