### ISSUE TITLE
Fix and Support for subtitles

### ISSUE THREAD

**Issue by rahaaatul** [nova-video-player/aos-AVP#517] opened 2021-12-06 14:06 UTC
I'm facing a subtitles problem with Nova. It displays random characters ![random characters](https://user-images.githubusercontent.com/86149861/144859816-dc2ffdeb-db80-4d84-869f-4d67224d7068.jpg) for the SSA subtitles in the nova video player. 

And also can you add function to select multiple subtitle at the same time?

TL;DR:

**Add support for most used SUBTITLE types including .SSA/.ASS.**

**Comment by courville** [comment] 2021-12-11 12:04
Can you please share the .ssa/.ass file?

**Comment by rahaaatul** [comment] 2021-12-11 12:45
> Can you please share the .ssa/.ass file?

[Here](https://drive.google.com/file/d/18JOV2koPRwdcjdmDhhf4xDIGr0ZN4V3j/view?usp=drivesdk) is the [.SSA/.ASS](https://drive.google.com/file/d/18JOV2koPRwdcjdmDhhf4xDIGr0ZN4V3j/view?usp=drivesdk) file (not the same shown in the screenshot but it'll do, I guess.

**Comment by rahaaatul** [comment] 2021-12-12 11:25
> @courville 
> Can you please share the .ssa/.ass file?

[Here](https://drive.google.com/file/d/18JOV2koPRwdcjdmDhhf4xDIGr0ZN4V3j/view?usp=drivesdk) is the [.SSA/.ASS](https://drive.google.com/file/d/18JOV2koPRwdcjdmDhhf4xDIGr0ZN4V3j/view?usp=drivesdk) file (not the same shown in the screenshot but it'll do, I guess).

**Comment by courville** [comment] 2021-12-18 15:30
Thanks for sharing the sample.
Nova has only very basic SSA sub support.
I guess the problem is in `SubtitleManager.java` with the parsing of the color tags.
```
// matches "{\c&Hcolor&}text" until end of input or next color tag
    private static final Pattern SSA_COLOR_TAG = Pattern.compile("\\{\\\\c&[h,H]([0-9,A-F,a-f]+)&\\}(.*?)(?=\\{\\\\c|$)");
```
Will try to find time to look at it.

**Comment by courville** [comment] 2021-12-18 15:53
@rahaaatul any chance you could find back the original picture sub?
What I see is that you have `{*\c&H3B41E5&}` tag and the `*` seems wrong somehow.
I do not see unfortunately why the crude simple replacement patterns in nova code would not work on the files provided as examples.

For now I am trying to fix the glitch and do not come up with an enhanced ssa support.

**Comment by rahaaatul** [comment] 2021-12-18 16:40
> @rahaaatul any chance you could find back the original picture sub?

Not really, I have deleted the file some time ago. But it's same with every SSA file. It's supposed to look like this ![this](https://user-images.githubusercontent.com/86149861/146648784-b444ee5f-dbf5-44a5-9a69-73d776a00364.jpg) but Nova shows it as text.

**Comment by rahaaatul** [comment] 2021-12-18 16:40
@courville 
> Any chance you could find back the original picture sub?

Not really, I have deleted the file some time ago. But it's the same with every SSA file. It's supposed to look like this ![Screenshot from MX Player](https://user-images.githubusercontent.com/86149861/146648784-b444ee5f-dbf5-44a5-9a69-73d776a00364.jpg) but Nova shows it as random character text.

**Comment by courville** [comment] 2021-12-18 18:10
@rahaaatul for now let's focus on the specific issue you depicted in the original issue: i.e. the tag still present in the text displayed. This should be easily fixed.

**Comment by rahaaatul** [comment] 2021-12-18 18:34
> @courville 
> For now let's focus on the specific issue you depicted in the original issue: i.e. the tag still present in the text displayed. This should be easily fixed.

The random character appears when there is `on video text` like the screenshot I posted hours ago appears, otherwise, the text subtitles seem fine with `.SSA` file. And also if the subtitle is animated, the random characters keep replacing each character, it's really terrible looking.


> For now let's focus on the specific issue you depicted in the original issue.

_To be honest, the original issue I posted was to let you know that instead of the text subtitle appearing on top of the video like the posted picture above, it shows random characters like the picture in the original issue._

**Comment by courville** [comment] 2021-12-18 18:39
@rahaaatul let's focus on the same issue, can you please share the video file and ssa file with software at courville dot org or provide the link to download the video? If you have the exact timestamp corresponding to the screenshot it would be nice. This way we will be synchronized on the issue to be solved. Thanks.

**Comment by rahaaatul** [comment] 2021-12-18 18:44
> @rahaaatul let's focus on the same issue, can you please share the video file and ssa file with software at courville dot org or provide the link to download the video? If you have the exact timestamp corresponding to the screenshot it would be nice. This way we will be synchronized on the issue to be solved. Thanks.

I will send you a comparison of Nova and another video player playing the same file tomorrow? Would that be okay?

Do you have telegram? I could send you the video there also.

**Comment by rahaaatul** [comment] 2021-12-18 18:45
@courville I will send you a comparison of Nova and another video player playing the same file tomorrow? Would that be okay? Or if you need the video, I could send it through telegram.

Do you have telegram?

**Comment by courville** [comment] 2021-12-18 18:46
@rahaaatul just the exact name of the video file could be enough, I will search it.

**Comment by rahaaatul** [comment] 2021-12-18 18:49
The original issue picture is an anime named **Attack on Titan**/ **Shingeki no Kyojin**.

Later provided subtitle file was from **Tokyo Revengers**.

Last Picture was from **Odd Taxi**.

**Comment by courville** [comment] 2021-12-19 11:26
OK I found Odd Taxi s01e01 and corresponding ass subs from the image you displayed.

**Comment by rahaaatul** [comment] 2021-12-19 11:35
I'm sorry I didn't see this message so the conversation dragged on...

> Nova has only very basic SSA sub support.

I hope you can implement full support for SSA subtitles in later updates of this app because Anime encoders use this type of subtitles to translate another language. So it's a crucial update required for nova to support SSA subtitles.

**Comment by courville** [comment] 2021-12-19 11:51
See https://github.com/nova-video-player/aos-AVP/issues/128 
Let's close this issue to avoid duplicate and continue discussion there.

**Closed as completed by courville** 2021-12-19 11:51 UTC
Labels: duplicate

**Comment by courville** [comment] 2022-12-10 17:01
Just a comment on this one it seems that color according to french tutorial https://sweetkaraoke.pagesperso-orange.fr/Tutoriels/Tutoriel4_1b.html is of the form `\<1/2/3/4>c&H<hex code>&`. I thus interpret the `*` as alternative for `\1` or `\2` or `\3` or `\4`. I can add this to the regexp.
