### ISSUE TITLE
[FEAT]: 不支持外挂字幕

### ISSUE THREAD

**Issue by liudehua333** [nova-video-player/aos-AVP#705] opened 2022-09-06 08:53 UTC
### Description

ass外挂字幕怎么使用，在线下载很麻烦，能不能本地读取外挂字幕

**Comment by seighero** [comment] 2022-09-07 03:49
可以使用外挂字幕，字幕文件与视频同名就可以了。

**Comment by nuo12138** [comment] 2022-09-10 00:33
> 

smb下可以，但是如果视频内嵌了很多字幕就不支持了，dlna模式下不支持，还是和nplayer可以手动选字幕那样比较方便
Smb mode support, If the video has a lot of subtitles embedded in it, it is not supported.dlna mode doesn't support!It is more convenient as nplayer can manually select subtitles

**Comment by Neverends4** [comment] 2022-09-19 03:24
dlna/upnp mode has limited external subtitles support by design, not the design of nova player, but the upnp/dlna protocol. Use smb if you want to use external subs.

**Comment by nuo12138** [comment] 2022-09-19 15:40
smb在无线网络环境下传输速度只有10mb/s，播放高码率视频会卡顿！如果nova player能支持webdav协议就好了！
The transmission speed of smb in the wireless network environment is only 10mb/s, and it will be stuck when playing high-bit rate video! It would be great if nova player could support webdav！

**Comment by nuo12138** [comment] 2022-09-19 15:42
webdav在无线环境下传输速度可以跑到70-80mb/s
The transmission speed of webdav can run to 70-80mb/s in a wireless environment

**Comment by courville** [comment] 2022-11-20 13:55
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/368
Let's follow this issue there.
Note: for higher speed support, use sftp instead meanwhile.

**Closed as completed by courville** 2022-11-20 13:55 UTC
Labels: duplicate, enhancement
