### ISSUE TITLE
[FEAT]: Default Audio Language 

### ISSUE THREAD

**Issue by Aco7777** [nova-video-player/aos-AVP#996] opened 2023-11-20 18:03 UTC
### Description

Hello.

Love the app but i wish it had an option to pick default audio language so i dont have to switch every time i want to watch something in another language (ex. a movie with 2 languages but the default one is not english), would that be possible to add in to the app?

Thanks in advance!

**Comment by Pentaphon** [comment] 2023-11-28 02:54
@courville duplicate of https://github.com/nova-video-player/aos-AVP/issues/334

**Comment by courville** [comment] 2023-11-29 10:16
Indeed, let's follow on the original issue. Thx

**Closed as completed by courville** 2023-11-29 10:16 UTC
Labels: duplicate, enhancement
