### ISSUE TITLE
[Bug]: F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [nova-video-player/aos-AVP#597] opened 2022-03-09 15:55 UTC
### Problem description

https://monitor.f-droid.org/builds/log/org.courville.nova/600049#site-footer

Could you please take a look? Thanks!

### Steps to reproduce the issue

I guess that's because ndk r23b is preinstalled so it's used but not supported.

### Your phone/tablet/androidTV model

None

### Operating system version

None

**Comment by courville** [comment] 2022-03-09 16:11
Slowly progressing here https://gitlab.com/software9/fdroiddata/-/tree/nova/novaV6Update on separate branch for an upcoming MR.
Note that getting a turnkey docker working to check build that is inline with fdroid CI is an adventure.
No clue however why it has been picked up by fdroid official monitor since there is no official tag on aos-Fdroid repo corresponding to 600049.

**Comment by linsui** [comment] 2022-03-09 16:38
That's weird. I'll look into it. Thanks for pointing that!

**Comment by courville** [comment] 2022-03-12 11:36
@linsui ok, it seems that my ongoing work has been merge when I asked a question about how to handle things causing the problem.
I witnessed this when creating my MR on fdroiddata which was conflicting.
Will redo a proper MR.

**Comment by linsui** [comment] 2022-03-12 11:45
Thanks!

**Comment by courville** [comment] 2022-03-12 11:50
Proper MR submitted https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10746

Note that build CI fails with a timeout (e.g. https://gitlab.com/software9/fdroiddata/-/jobs/2192527632 since gitlab since is having some issues). However it has been "verified" to compile using https://gitlab.com/fdroid/docker-executable-fdroidserver for which you need to setup yourself the Android SDK etc... This was quite a journey to complete the verification (thanks to https://marc-walter.info/posts/2019-07-12_build_fdroid/ providing some hints). Perhaps I have not looked hard enough but I failed to find ways to use the official fdroid build docker. I thus took a leap of faith there with the MR.

I tried to verify the best I could on my side.

**Comment by courville** [comment] 2022-03-12 15:34
For the record, as pointed out by linsui, timeout can be extended to 3h in project settings, CI pipelines (search for timeout). This should help.

**Comment by courville** [comment] 2022-03-13 09:31
@linsui thanks for your support!

**Comment by courville** [comment] 2022-03-16 05:56
@linsui bad news https://monitor.f-droid.org/builds/log/org.courville.nova/600052#site-footer
CI passes but "real build" fails. The issues seems to be that cmake is not found or sdkmanager for opus.
```
NDK_PATH is /opt/android-sdk/ndk/23.1.7779620
build.sh: line 29: sdkmanager: command not found
build.sh: line 30: sdkmanager: command not found
CMAKE_PATH is
~/build/org.courville.nova/native/opus-android-builder/build-armeabi-v7a ~/build/org.courville.nova/native/opus-android-builder
build.sh: line 46: /bin/cmake: No such file or directory
ninja: error: loading &#39;build.ninja&#39;: No such file or directory
```
I will look into it.
Note to self, it seems that same lines and path are working a couple of lines above the same script and other `native/*/build.sh` scripts too and ` sdkmanager "${cmake}"` is failing:
```
# android sdk directory is changing
[ -n "${ANDROID_HOME}" ] && androidSdk=${ANDROID_HOME}
[ -n "${ANDROID_SDK_ROOT}" ] && androidSdk=${ANDROID_SDK_ROOT}
# multiple sdkmanager paths
export PATH=${androidSdk}/cmdline-tools/latest/bin:${androidSdk}/cmdline-tools/bin:$PATH
NDKVER=23
if [ ! -d "${androidSdk}/ndk-bundle" -a ! -d "${androidSdk}/ndk" ]
then
  ndk=$(pkg="ndk;$NDKVER"; sdkmanager --list | grep ${pkg} | sed "s/^.*\($pkg\.[0-9\.]*\
  yes | sdkmanager "${ndk}" > /dev/null
  echo NDK $ndk installed
fi
[ -d "${androidSdk}/ndk-bundle" ] && NDK_PATH=${androidSdk}/ndk-bundle
[ -d "${androidSdk}/ndk" ] && NDK_PATH=$(ls -d ${androidSdk}/ndk/* | sort -V | tail -n 1
echo NDK_PATH is ${NDK_PATH}
if [ ! -d "${androidSdk}/cmake" ]
then
  cmake=$(pkg="cmake"; sdkmanager --list | grep ${pkg} | sed "s/^.*\($pkg;[0-9\.]*\).*$/
  sdkmanager "${cmake}"
fi
# latest cmake
[ -d "${androidSdk}/cmake" ] && CMAKE_PATH=$(ls -d ${androidSdk}/cmake/* | sort -V | tai
echo CMAKE_PATH is ${CMAKE_PATH}
```

**Comment by linsui** [comment] 2022-03-16 07:00
See https://gitlab.com/fdroid/fdroiddata/-/blob/master/.gitlab-ci.yml#L256. sdkmanager from pip is only included in the CI for test. In the buildserver you need to use

```
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 $$SDK$$/tools/bin/sdkmanager 'cmake;3.18.1'
        > /dev/null
```

**Comment by courville** [comment] 2022-03-16 17:41
@linsui, thanks for pointing this out. It is disturbing that the CI and build server are different but fine let's try to adapt.
This means that for now I just need to use the default `PATH` `${androidSdk}/tools/bin`
```
export PATH=${androidSdk}/cmdline-tools/latest/bin:${androidSdk}/cmdline-tools/bin:${androidSdk}/tools/bin:$PATH
```
Now the real question is how to I cope with the java8/11 schizophrenia? All new sdkmanager versions are java11 and the one f-droid is using is java8.

For the record, all latest Android `sdkmanager` are provided part of `cmdline-tools` and are located first in `${androidSdk}/cmdline-tools/bin` and after upgrade of current Google reference package the latest binary is in `${androidSdk}/cmdline-tools/latest/bin` (yes I know disturbing and why Google keeps changing things...). Moreover for the "little story" latest `${androidSdk}/tools/bin/sdkmanager `requires a `--sdk_root=` parameters but not `${androidSdk}/cmdline-tools/latest/bin/sdkmanager` one (but this is another story).
Ah I forgot, all new sdkmanager versions are java11 and the one you are using is java8.

Do not worry I will figure a gaz plant that will handle f-droid and my current other build environment.

**Comment by courville** [comment] 2022-03-16 19:04
@linsui I propose to do:
```
prebuilt:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 $$SDK$$/tools/bin/sdkmanager 'cmake;3.18.1' 'cmdline-tools;latest' platform-tools 'build-tools;30.0.3' > /dev/null
```
Will provide an MR.

**Comment by courville** [comment] 2022-03-17 19:01
See https://gitlab.com/software9/fdroiddata/-/commit/a6656afbecdf68745707d88acfe3c08190e0db11

**Comment by courville** [comment] 2022-03-17 19:45
@linsui seems that I am not the only one having sdkmanager paths issues:
```
bash:  /opt/android-sdk/tools/bin/sdkmanager: No such file or directory
```
Thus in the official f-droid build docker it is located elsewhere.
EDIT1: Adding `find $$SDK$$ -name sdkmanager` to find out...
EDIT2: Uh other yml have `$$SDK$$/tools/bin/sdkmanager` too --> but long ago
EDIT3: confirmed to be /opt/android-sdk/tools/bin/sdkmanager, trying without `yes`
EDIT5: better but no love for prebuild target
```
2022-03-17 21:29:29,675 DEBUG: > bash -x -c -- JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /opt/android-sdk/tools/bin/sdkmanager 'cmake;3.18.1' 'cmdline-tools;latest' platform-tools 'build-tools;30.0.3' > /dev/null
+ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
+ /opt/android-sdk/tools/bin/sdkmanager 'cmake;3.18.1' 'cmdline-tools;latest' platform-tools 'build-tools;30.0.3'
Warning: File /home/vagrant/.android/repositories.cfg could not be loaded.
Warning: Failed to read or create install properties file.
2022-03-17 21:29:41,404 ERROR: Could not build app org.courville.nova: Error running prebuild command for org.courville.nova:6.0.53
```
EDIT5: use init instead of prebuild target

**Comment by linsui** [comment] 2022-03-18 02:33
That's weird... It works for me.

```
2022-03-18 01:56:04,855 DEBUG: Directory: build/org.courville.nova/Video
2022-03-18 01:56:04,856 DEBUG: > bash -x -c -- JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /opt/android-sdk/tools/bin/sdkmanager 'cmake;3.18.1' > /dev/null
+ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
+ /opt/android-sdk/tools/bin/sdkmanager 'cmake;3.18.1'
Warning: File /home/vagrant/.android/repositories.cfg could not be loaded.
2022-03-18 01:56:17,685 INFO: Cleaning Gradle project...
```

**Comment by courville** [comment] 2022-03-18 17:51
OK I found what was wrong on my side.
Here you go: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10776

**Comment by courville** [comment] 2022-03-21 09:27
OK closing the issue now cf. https://monitor.f-droid.org/builds/log/org.courville.nova/600053#site-footer

**Closed as completed by courville** 2022-03-21 09:27 UTC
Labels: bug
