### ISSUE TITLE
Feature Request to add support for Bluray PGS subtitles

### ISSUE THREAD

**Issue by Unix-Kernel** [nova-video-player/aos-AVP#498] opened 2021-10-23 01:55 UTC
Please consider adding support for Bluray PGS (zlib) subtitles.

**Comment by courville** [comment] 2021-12-19 13:49
Still in the todo's list (help wanted). Closing since duplicate of https://github.com/nova-video-player/aos-AVP/issues/47

**Closed as completed by courville** 2021-12-19 13:49 UTC
Labels: duplicate
