### ISSUE TITLE
Add to Library not working

### ISSUE THREAD

**Issue by n0cturn** [nova-video-player/aos-AVP#277] opened 2020-01-14 13:20 UTC
Ive got a strange issue with the 'add to library' not working after a day or two with any video on network drives. Ive tried various versions including the latest 4.29. If i uninstall and install fresh it will index all the media on network, but after a couple of days any new files cant be added to library. Am i missing something obvious? i never had this issue with Archos video player

**Comment by courville** [comment] 2020-01-18 16:03
Thanks for reporting. Is the behavior present on TV or phone/tablet?
Could you try when it happens to force close the app via settings and see if the issue is still present when relaunching the app?

**Comment by n0cturn** [comment] 2020-01-18 18:18
Hi, sorry I should have said what system I was running it on. Its a Rockchip Tv box, the H96 max+

Its got even stranger.... the last time it refused to add new video to library i uninstalled and reinstalled (v4.29) to find i now couldnt add any network video to library. It indexed the folders and could see the files but nothing was auto added to library. I then unnistalled again and installed the previous version with the same result. I tried a few versions but i couldnt add to library any network file until i installed v5.7 beta so maybe its a network issue (my nas drive is quite old so doesnt use SMB2)

I will try the force close to see if that helps, i'll also see if the issue happens installed on my phone to see if its device specific (am i the only person thats experienced this?)

**Comment by courville** [comment] 2020-01-18 19:27
The issue you experience could be caused to some recent changes on foreground services that needs now to be stopped. Relaunching app making it working could be an indication of this symptom...

**Comment by n0cturn** [comment] 2020-01-25 05:26
Unfortunately I still have this issue even with the newer versions, it seems to let me add videos a couple of times (a few days apart) and the third time it just shows the add to library button which does nothing when pressed on

I have tried force closing Nova and then restarting, but that didnt help.

**Comment by courville** [comment] 2020-01-25 19:29
Do you see in logcat when you hit add to library something like:
```
2020-01-25 20:27:34.637 18228-18250/org.courville.nova W/MessageQueue: Handler (android.os.Handler) {86a56e7} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {86a56e7} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.post(Handler.java:403)
        at android.database.ContentObserver.dispatchChange(ContentObserver.java:200)
        at android.database.ContentObserver.access$000(ContentObserver.java:28)
        at android.database.ContentObserver$Transport.onChange(ContentObserver.java:233)
        at android.database.IContentObserver$Stub.onTransact(IContentObserver.java:98)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```
If this is the case could you please tell me if your network setup is specific?

**Comment by courville** [comment] 2021-12-19 23:09
It should be fixed in recent releases.

**Closed as completed by courville** 2021-12-19 23:09 UTC
