### ISSUE TITLE
[FEAT]: Unable to read IOS file. Please add support

### ISSUE THREAD

**Issue by lubaohua** [nova-video-player/aos-AVP#876] opened 2023-04-21 03:10 UTC
### Description

I really like NOVA. He has excellent poster wall functionality, but it is currently unable to read my IOS files

**Comment by courville** [comment] 2023-04-22 10:51
Hi, when you are referring to IOS files, do you mean video shot from an iphone?
Please provide sample so that we can progress on the issue.

**Comment by lubaohua** [comment] 2023-05-07 02:01
Ant-Man.and.the.Wasp.Quantumania.2023.WEBRip.x264.ios

**Comment by lubaohua** [comment] 2023-05-07 02:01
It's in this format

**Comment by phhusson** [comment] 2023-05-07 13:50
I've asked some people noone has ever heard of that. Can you provide us with a downloadable link?

**Comment by lubaohua** [comment] 2023-05-13 05:08
magnet:?xt=urn:btih:12183b3a947e15808473b215752289fdddd5de63

**Comment by phhusson** [comment] 2023-05-13 09:42
That's an iso, not ios.

**Comment by courville** [comment] 2023-05-13 09:50
Closing as duplicate of https://github.com/nova-video-player/aos-AVP/issues/450

**Closed as completed by courville** 2023-05-13 09:50 UTC
Labels: duplicate, enhancement

**Comment by lubaohua** [comment] 2023-05-18 16:17
Oh okay, I made a mistake. Where can I add support

**Comment by ghost** [comment] 2023-05-18 16:32
Iso is not really a video file, but a disk image to be burned on disk or mounted as a virtual drive. While some players can handle iso o doubt it's worth it for nova. Mount the iso as a drive and then rip it to an mkv file instead.

**Comment by lubaohua** [comment] 2023-05-24 02:04
Do you want Nova to recognize ISO format? Many players support playing ISO format videos directly
