### ISSUE TITLE
Episodes dont disappear after deleting even though they are successfully deleted

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#732] opened 2022-10-26 17:40 UTC
Basically title. This happens in the newest current version.

**Comment by mitch133** [comment] 2022-10-26 17:43
https://github.com/nova-video-player/aos-AVP/issues/722

**Comment by courville** [comment] 2022-10-27 18:07
Thanks for reporting closing as duplicate of #722
Let's follow the resolution there.

**Closed as completed by courville** 2022-10-27 18:07 UTC
