### ISSUE TITLE
[壮举]：Are U add support for WebDAV ?

### ISSUE THREAD

**Issue by showlee** [nova-video-player/aos-AVP#696] opened 2022-08-01 16:07 UTC
### Description

Are U add support for WebDAV ?

### Additional information

Are U add support for WebDAV ?

**Comment by Pentaphon** [comment] 2022-08-03 18:45
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/368

**Closed as completed** 2022-11-20 13:53 UTC
Labels: duplicate, enhancement
