### ISSUE TITLE
[Bug]: Search movie functionality not working

### ISSUE THREAD

**Issue by mitch133** [nova-video-player/aos-AVP#654] opened 2022-06-15 20:19 UTC
### Problem description

Nova finds the file but cannot play it

### Steps to reproduce the issue

When using the search button (i.e in "all movies") the movie is correctly found, but without any description (even when already/previously added/recognized by Nova).

In addition, the path to the file is correctly identified, but it is impossible to play it. An error message is displayed saying that the file cannot be played.

So there's no alternative to play it but to scroll in the menu till you find it.

It's just useful to check if the movie is here

### Expected behavior

Find the movie with proper description and ability to play it

### Your phone/tablet/androidTV model

Samsung Galaxy S21

### Operating system version

Android 12

### Application version and app store

6.0.67 fron google play store

### Additional system information

Works fine on Android TV (Freebox pop)

**Comment by courville** [comment] 2022-06-19 10:44
Valid report but duplicate of https://github.com/nova-video-player/aos-AVP/issues/655 which has been fixed (not released yet).

**Closed as completed by courville** 2022-06-19 10:44 UTC
Labels: bug, duplicate
