### ISSUE TITLE
[Bug]: After Update to "Nvidia Shield Experience 9.0" (Android 11 Update) NOVA no longer recognizes/scans media files

### ISSUE THREAD

**Issue by mayham99** [nova-video-player/aos-AVP#539] opened 2022-01-13 09:24 UTC
### Problem description

After upgrading to the latest Nvidia Shield version NOVA no longer shows the Movies/Series from my external Harddrive (with scraped Images and imformations).

It is still possibel to navigate to the files and play them. But of course i want them with cover and everything in the overview.

It looks like many people (an many other software developers) got similar issues with accessing the files on an external drive under Android 11 - some more informations in the official Nvidia forum: https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481350/shield-experience-upgrade-90-released-11222/

Nvidia says the developers of the apps have to update their apps to work again.

i hope this is all correct and understandable as this is my first entry which is exclusivly have signed up for :)

Thanks in advance

### Steps to reproduce the issue

- Update the Nvidia Shield to Shield Experience 9.0 (Android 11)
- start NOVA and see if you media files are shown in the Movies and Series sections

--> Nvidia says this is a generall "problem" with Android 11 (not only on the Shield) because Android changed something from Android 9 to 11 under the hood

### Your phone/tablet/androidTV model

NVidia Shield 2019 Pro

### Operating system version

Android 11 (Shield Experience 9.0)

**Comment by courville** [comment] 2022-01-13 09:34
Thanks for pointing this out. I will upgrade my nvidia shield and test.
Note that pre-release v6.0.xx of nova is complying with API31 Android "features" i.e. new security limitations, it could help.
I am not clear if it will solve the issue though.

**Comment by mayham99** [comment] 2022-01-13 09:48
Thanks for the quick response.

As i am not a developer i don't know how i can compile/create a "pre-release" for myself. But that is no problem. I'm waiting for the final update via the playstore.

As you marked this as important, i assume there might be a fix in one of the next releases.

Thank you very much for the work. NOVA is really a great player :)

best regards

**Comment by courville** [comment] 2022-01-13 09:55
Pre releases are available here: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.36

**Comment by courville** [comment] 2022-01-13 23:03
OK I can reproduce and this is not specific to external storage, it is also valid for internal storage. What is strange is that it does not happen on any phone I have tested with Android 11 and 12...
Note to self:
- files are visible in android mediadb  `adb shell content query --uri "content://media/external/video/media" --projection _data`
- files are imported in nova mediadb `adb shell content query --uri "content://com.archos.media.videocommunity/raw/files_import" --projection _data`
- files are not seen as video files by nova
```
adb shell content query --uri "content://com.archos.media.videocommunity/external/video/media"
No result found.
```
I had to enable in shield settings storage multimedia analysis (off by default really?).

**Comment by courville** [comment] 2022-01-13 23:09
@mayham99 until I figure it out, the workaround for you is to enable file sharing on your hdd on the shield that will expose the hdd as SMB share and go in nova network, authenticate and then index the SMB share corresponding on your hdd.
It works.

**Comment by mayham99** [comment] 2022-01-14 07:52
Thank you very much courville

first of all for providing the link to the pre-release versions. I did not use any of them yet as i did not know which one would be the right one for my shield and i was a bit deterred by the info that the database will be rebuild and i cannot switch back that easily...

but on the other hand this was OK but now i could try your workaround and can confirm that this worked perfectly on my end as well - thanks :)

just one question for the future: When this will hopefully be fixed in one of the next versions, i assume i have to deactivate the SMB share/indexing again, because otherwise i will have every movie and series twice in my list right?
--> But that will then be just some editing in the settings - i'm happy that you found this nice workaround so fast

best regards

**Comment by Cowboy1968** [comment] 2022-01-14 18:04
Hi courville,

I am having the same issue and I'm a bit confused about your workaround.

"the workaround for you is to enable file sharing on your hdd on the shield that will expose the hdd as SMB share and go in nova network, authenticate and then index the SMB share corresponding on your hdd.
It works."

I already have file sharing on my shield as I access the usb drive (set up as removable storage on the shield) via my home network.  Are you saying I should now instead of just scanning my attached hard drive for shows I should browse it as an SMB (NAS) drive?  Do I use the lgin info I use to access the rive from my home network (the log in info provided by the shiled when I turned on file sharing over network)?

Hopefully, that made some sense

Thanks

**Comment by courville** [comment] 2022-01-14 20:07
Browsing through SMB only did the trick to me scanning the usb drive after exposing the usb drive as SMB share in Android settings -> Storage setting.

Note that for some reason on the latest build I tested all the files on local storage and USB drive are scanned properly now (I do not understand what has changed). I will publish the associated version as pre-release on github this evening.

**Comment by Cowboy1968** [comment] 2022-01-14 23:55
Is this v6.0.37 the new version to fix the USB drive scanning?

 

Thanks

 

Tim

 

 

From: CourvilleSoftware ***@***.***>
Reply-To: nova-video-player/aos-AVP ***@***.***>
Date: Friday, January 14, 2022 at 12:07 PM
To: nova-video-player/aos-AVP ***@***.***>
Cc: Tim Allen ***@***.***>, Comment ***@***.***>
Subject: Re: [nova-video-player/aos-AVP] [Bug]: After Update to "Nvidia Shield Experience 9.0" (Android 11 Update) NOVA no longer recognizes/scans media files (Issue #539)

 

Browsing through SMB only did the trick to me scanning the usb drive after exposing the usb drive as SMB share in Android settings -> Storage setting.

Note that for some reason on the latest build I tested all the files on local storage and USB drive are scanned properly now (I do not understand what has changed). I will publish the associated version as pre-release on github this evening.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cowboy1968** [comment] 2022-01-17 00:04
Hi, I just installed and tried v6.0.37 Google play internal (non public) release as I assumed it was the version you mentioned in your comment below

"Note that for some reason on the latest build I tested all the files on local storage and USB drive are scanned properly now (I do not understand what has changed). I will publish the associated version as pre-release on github this evening."

This version unlike the previous version of Version 6 now shows the "dvd covers" not just grey boxes, so thats good. There was one issue with cover art though, and I am not sure if its consistent issue as only one show scanned in wrong.  HAWKEYE, scanned in as an older version of the show (https://www.imdb.com/title/tt0108798/).  So I changed the name to HAWKEYE 2021 and it found the correct show, (https://www.imdb.com/title/tt10160804/) and changed the info, but the dvd and episode art stayed as the older show. 

But, where the previous version of 6 and version 5's saw my USB connected drive files, this version saw them as empty folders.  Specifically, It saw the TV and Movie Folders, but when you go into the Movie folders it shows as completely empty (but there are sub folders for each movie), the TV folder when you go into it shows all the tv show sub folders. When you go into the tv series sub folder they show as all empty.  So I am not sure if it would scan the USB drive as it showing it as empty of actual video files so nothing to scan in, if it did see the video files maybe it would scan from it??

There were also several shows again that version 5 scanned in fine that this and the previous version did not
-Fast Food Mania
-Food Factory Canada (it scanned it in as the US version)
-Haunted Encounters Face to Face
-The Secret Life of our Pets
-John Doe

So now I am back on verion 5 (the one available in the playstore)and have connected my external drive to my router as a pseudo NAS, but I do hope USB drive scanning will be fixed some time soon.

Thank you for all your hard work and an amazing piece of software!

**Comment by courville** [comment] 2022-01-17 09:24
Note that I have updated [Nova FAQ](https://home.courville.org/nova_video_player-faq/index.html) to state that:

> In order to identify multimedia files, Nova relies on Android media scanning for local storage and USB storage. On latest version of the OS, Nvidia shield disables external storage Android indexing for performance enhancements. In order to get back external storage video files visibility, you need to enter Android settings/Device Preferences/Storage and enable Scan for media automatically option.

External USB drive scanning **_needs to be enabled_**.

Can you check that it solves your visibility issue (it will take time to scan the drive)?

Regarding TV shows identification, it is normal that Hawkeye is identified as the old show. Correct naming convention is that when there is a show with same name it needs to specify first air date in the title but not all are complying indeed as I witness here https://eztv.re/search/hawkeye where 2021 is missing sometimes...

**Comment by T2336** [comment] 2022-01-17 10:49
> External USB drive scanning **_needs to be enabled_**.

v6.0.37 and this setting enabled fixed the issue of the empty folders for me. Thank you!

**Comment by Cowboy1968** [comment] 2022-01-17 16:31
Thanks for the quick reply and fix, I will look at that tonight!  

Re Hawkeye, I manually added 2021 to each episode via NOVA and NOVA **found the right info,** but the dvd art would not change and kept showing the dvd cover for the older incorrect show.  I am going to try to add 2021 to the actual title of the show before letting NOVA scan the drive and see if it finds the right show first thing.

Thanks so Much

**Comment by courville** [comment] 2022-01-18 06:48
@Cowboy1968 I will look at the poster not changing, this sounds like a bug.

EDIT: I confirm the bug and `ManualShowScrappingSearchFragment` sets only episode poster and not the season/show one. TODO: check backdrop too.

**Comment by courville** [comment] 2022-01-19 19:36
Regarding the issue itself, plex has issues too of course https://www.androidpolice.com/android-11-nvidia-shield-breaking-apps-plex-servers/ and any other app that is targeting API30+ (which is mandatory to update app on playstore) due to scope storage enforcement (cf. https://github.com/nova-video-player/aos-AVP/issues/336). Seems that nvidia will revert their 'do not scan usb drive' change.

**Comment by Cowboy1968** [comment] 2022-01-19 22:03
Hi, well I am still stuck here. Hi, I just installed  v6.0.37 after uninstalling the old playstore ver 5 (after clearing cache and data and rebooting first.  Then I went and enabled External USB drive scanning as well as ensured Nova had permission to access storage.  Then I rebooted and opened Nova and it has been sitting there with the scanning icon for 15 minutes without anything scanning in.  I browsed in nova to my external drive to ensure that the drive and the files can be seen and accessed and they can.  So I am not sure why its stuck (not frozen) at scanning.

**Comment by Cowboy1968** [comment] 2022-01-19 22:04
Sorry forgot to mention I also tried to manually 
add to library and nothing happened

**Comment by Cowboy1968** [comment] 2022-01-19 23:12
Well it has been an hour and it has not scanned anything in, so I went back to accessing my NAS which I use for back up.  Unfortunately the newest version is still not scanning in quite a few shows (shows no tv show info found). The weird thing is that if I got to the MovieDB website and search for the show there, it is found without issue.  I double check the info/naming of the file and it is correct (and is found by version 5 without issue using theTVDB).  These shows include John Doe, Walker Texas Ranger, Food Network Canada, Inside the zoo and several more.  The good thing though is adding 2021 to the Hawkeye file name for each episode correctly scanned them in as the 2021 show.  

Thanks for all your hard work!

**Comment by Cowboy1968** [comment] 2022-01-19 23:28
Okay I am not sure if Nvidia has already removed the do not scan usb drive part, but I don't think so as I had to go back into settings and turn off auto scan external HDD for media as Nova was stuck at trying to read the drive and I could not scan in anything via my NAS.  After I found that the newer version failed to scan in several shows, I uninstalled 6 rebooted and went back to 5 from the playstore, as soon as I opened it it starting scanning my usb drive???!!! So I am not sure what happened, the option to turn on scan external HDD for media is still there and turned off, so I am not sure how or why version 5 is scanning my usb drive, I am just happy it is

**Comment by mayham99** [comment] 2022-01-20 07:30
Hello everyone

i just wanted to give some feedback how it all turned out for as i was able to test some of the new ideas yesterday:

So first of all i never updated NOVA to version 6 because i was to affraid of the whole "internal database will change" situation. I want to wait for the final release if possible.

The fist workaround with the SMB sharing worked fine for me and i had all my Movies and Shows again in the overview. I can confirm that a show sometimes is not found correctly but that for me was always the case and is most of the time with some adjustments to the name possible -> so no real problem for me here.

Yesterday i tried the "enter Android settings/Device Preferences/Storage and enable Scan for media automatically option" solution and that worked perfectly as well for me. At first i had obviously every entry twice (one from local USB and one from SMB) in the system but i just deactivated (removed the folder from scanning) the SMB workaround again and now everything is back to how it was. Version 5 with access to USB.

It looks/sounds like the solution works for some and not for others?!?! I just want to confirm, that it worked for me and that i did not had to upgrade NOVA to v6.

best regards

**Comment by mayham99** [comment] 2022-01-20 08:18
Hi

i just stumbled upon this: https://www.androidcentral.com/nvidia-promises-fixes-broken-plex-kodi-and-more-nvidia-shield-tv-after-android-11-update

There are some fixes/workarounds listed:

- You can re-grant storage permissions to get individual apps like VLC working again. In Settings, navigate to Apps > Select your app > Permissions > Files and Media > Allow all the time (or Allow depending on the app).
- Some users have regained functionality by uninstalling and reinstalling an app.
- Enable external storage and network-attached storage to be seen as it's connected. In Settings, navigate to Device Preferences > Storage > Scan for media automatically.
- Kodi's remote server streaming issue has a workaround that involves disabling the usage of http2.
- Some users have fixed most issues by factory resetting, but signing back into all your apps is a big fat pain, even with the improved Google Keyboard.

Maybe this helps too

**Closed as completed** 2024-07-01 14:26 UTC
Labels: bug, Important
