### ISSUE TITLE
[FEAT]: WebDAV

### ISSUE THREAD

**Issue by onlytanmoy** [nova-video-player/aos-AVP#836] opened 2023-03-05 21:09 UTC
### Description

Hiya, please provide option to add WebDAV to browse the files stored there and then play them via Nova Player.

**Comment by phhusson** [comment] 2023-03-05 21:39
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/368 and already in progress

**Closed as completed by phhusson** 2023-03-05 21:39 UTC
Labels: enhancement
