### ISSUE TITLE
inbuilt subtitles are not showing on videos

### ISSUE THREAD

**Issue by sunilroy007** [nova-video-player/aos-AVP#465] opened 2021-08-23 21:41 UTC
not even one video shows subtitles which are inbuilt and pgs type. other video players shows it but i like nova player for trakt support and posters and night mode sound

please fix subtitles issue , i know i can download from online option but they are always messed up not good

**Comment by courville** [comment] 2021-08-24 09:33
Sadly nova does not support yet PGS subtitles.
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/47, thus closing this issue.

**Closed as completed by courville** 2021-08-24 09:33 UTC
Labels: duplicate
