### ISSUE TITLE
App crashes when trying to access OneDrive content

### ISSUE THREAD

**Issue by newme21** [nova-video-player/aos-AVP#446] opened 2021-04-27 09:32 UTC
When accessing content from my OneDrive the app crashes

 If you click cloud on the app it brings up the android file manager and when I select my file from the OneDrive the app would crash.

Samsung s10e android

**Comment by courville** [comment] 2021-12-20 21:49
Closing as duplicate of https://github.com/nova-video-player/aos-AVP/issues/337

**Closed as completed by courville** 2021-12-20 21:49 UTC
Labels: duplicate
