### ISSUE TITLE
It is recommended to add support for WebDAV protocol

### ISSUE THREAD

**Issue by showlee** [nova-video-player/aos-AVP#697] opened 2022-08-01 16:09 UTC
### Description

It is recommended to add support for WebDAV protocol

### Additional information

It is recommended to add support for WebDAV protocol

**Comment by Pentaphon** [comment] 2022-08-03 18:46
Duplicate of https://github.com/nova-video-player/aos-AVP/issues/368

Please don't open 2 of the same issue.

**Closed as completed** 2022-11-20 13:53 UTC
Labels: duplicate, enhancement
