### ISSUE TITLE
Online streaming playback from other applications

### ISSUE THREAD

**Issue by Unix-Kernel** [nova-video-player/aos-AVP#458] opened 2021-07-19 01:37 UTC
Using v5.15

It seems that Nova does not support video streaming from the internet (http) when trying open them from other applications.

For example, when using Cinema, Tivimate, or Kodi and trying to use Nova to playback the online streams, nothing happens and the screen goes black. 

I may be wrong but I don't think that Nova supports playback from http-internet streams, is this correct?

Is there a way to backup the settings? If not, this would be a good feature to add (import/export settings).

**Comment by courville** [comment] 2021-07-22 12:07
Hi,

you are right in the sense that nova supports only http (not https)
streaming for now.

BR,

**Comment by Unix-Kernel** [comment] 2021-07-22 13:48
Ok, thanks

**Comment by courville** [comment] 2021-12-19 18:38
Closing as duplicate of https://github.com/nova-video-player/aos-AVP/issues/23, let's follow issue there.

**Closed as completed by courville** 2021-12-19 18:38 UTC
Labels: duplicate
