### ISSUE TITLE
Embedded subtitle cant be chosen

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#480] opened 2021-09-16 17:18 UTC
Basically you cant choose or even if you choose it doesn't show the subtitles, not sure how İ can help with this issue other than sending the episode file itself.

**Comment by courville** [comment] 2021-09-21 15:54
If these embedded subs are PGS subs it is normal since nova does not support it yet cf. https://github.com/nova-video-player/aos-AVP/issues/47

**Comment by okan35** [comment] 2021-09-22 06:57
I don't know if it is PGS, I just know that vlc is able to show in subtitle choices while nova does not show at all in subtitle choices. I will check if it is PGS.

**Comment by courville** [comment] 2021-09-27 18:16
Closing the issue as duplicate of https://github.com/nova-video-player/aos-AVP/issues/47 until proven wrong (feel free to reopen issue if this is not the case).

**Closed as completed by courville** 2021-09-27 18:16 UTC
Labels: duplicate
